### ISSUE TITLE
Refresh failed in rails 5.1.0

### ISSUE THREAD

**Issue by geekerzp** [dgutov/robe#101]
<img width="1034" alt="2017-03-09 5 43 01" src="https://cloud.githubusercontent.com/assets/2854886/23744614/deeb5f94-04ef-11e7-81f8-75253b94152b.png">

**Comment by geekerzp** [comment]
@dgutov pls have a look, thanks

**Comment by dgutov** [comment]
Thanks for the report (no need to @ me personally, BTW). Please try this in the console:

```rb
Rails.application.reloader.reload!
```

Does it work okay?

**Comment by geekerzp** [comment]
Found the reason that Rails 5.1 has removed the `.to_prepare`, `.to_cleanup`, `.prepare!` and `.cleanup!` from ActionDispatch::Reloader.
<img width="945" alt="2017-03-13 9 42 39" src="https://cloud.githubusercontent.com/assets/2854886/23838536/de789b96-07d1-11e7-9fd7-67cc1679fb8f.png">
@dgutov

**Comment by dgutov** [comment]
Please try this patch:

```diff
diff --git a/lib/robe/sash.rb b/lib/robe/sash.rb
index f3ef230..c01c5d2 100644
--- a/lib/robe/sash.rb
+++ b/lib/robe/sash.rb
@@ -173,8 +173,12 @@ module Robe
     end
 
     def rails_refresh
-      ActionDispatch::Reloader.cleanup!
-      ActionDispatch::Reloader.prepare!
+      if defined?(Rails.application.reloader)
+        Rails.application.reloader.reload!
+      else
+        ActionDispatch::Reloader.cleanup!
+        ActionDispatch::Reloader.prepare!
+      end
       Rails.application.eager_load!
       init_name_cache
     end
```

**Comment by geekerzp** [comment]
Very appreciate!

**Comment by dgutov** [comment]
I'm assuming you've tried the patch by now, so applying.
