### ISSUE TITLE
Searching for program: No such file or directory, bundle

### ISSUE THREAD

**Issue by tjbrn** [dgutov/robe#110]
Hello, I don't know if this behavior is considered normal, but if a open emacs, then open a ruby project and try to `robe-start`, i get this error:
![screenshot_20171107_121825](https://user-images.githubusercontent.com/10359351/32501251-4eec98f0-c3b6-11e7-85d0-baffe9a79ba7.png)

But if I start emacs from terminal, inside of the project folder(`emacs ~/some-project`) robe just works normally.

There is a bundle directory inside the project
`.bundle  db  .git  app.rb  bot.rb  config.ru  environment.rb  Gemfile  Gemfile.lock  .gitingore  Rakefile`

and `pry` gem is installed

this continues to happen even with a minimal config
```
...
(use-package robe
  :ensure t
  :defer t
  :init
  (add-hook 'ruby-mode-hook 'robe-mode))
```
(apparently the problem isn't my config, this happens even in spacemacs)

Do I have to open emacs in the project directory from terminal every time I need to use`robe-start`?

**Comment by dgutov** [comment]
That would depend on which tools you're using for Ruby project management. In general, you have to configure your Emacs to work with it before trying Robe.

See also these reports: https://github.com/dgutov/robe/issues?utf8=✓&q=is%3Aissue%20No%20such%20file%20or%20directory%2C%20bundle%20is%3Aclosed%20

I always use GUI Emacs, and my rbenv configuration resides in `~/.config`. That's all that is requires for this to work, on my system.

**Comment by tjbrn** [comment]
Currently I'm not using rbenv nor rvm, my unique ruby configuration is

```
# bashrc
# this config let me "gem install" without sudo
if which ruby &>/dev/null && which gem &>/dev/null; then
  export GEM_HOME="/home/username/.gem/ruby/2.4.0"
  export GEM_PATH=$GEM_HOME
  if [[ ! "$PATH" == *$GEM_HOME/bin* ]]; then
    export PATH="$PATH:$GEM_HOME/bin"
  fi
fi
```

I did a test again, and confirmed that if I open Emacs from desktop(I'm using KDE/openbox) this error occurs, but openning Emacs from terminal(GUI or without window, now no matters what is the initial directory) robe just works

I'm using robe mainly because the integration with company

Could it be because applications initialized from desktop can't know about my bash config?

**Comment by dgutov** [comment]
> Could it be because applications initialized from desktop can't know about my bash config

Pretty much, yes. When it's not launched from Bash.

But you can try putting this piece of code into `~/.profile`. Relogin (or restart) afterwards.

**Comment by tjbrn** [comment]
Putting the configuration into `~/.bash_profile` solved the problem!
(trying the same thing with `~/.profile` didn't work, maybe because bash zoo)

So, for someone, as me, that doesn't uses rvm/rbenv, just put this code into your ~/.bash_profile and things should just works!
```
# "gem install" without sudo
if which ruby &>/dev/null && which gem &>/dev/null; then
  export GEM_HOME="$(ruby -rubygems -e 'puts Gem.user_dir')"
  if [[ ! "$PATH" == *$GEM_HOME/bin* ]]; then
    export PATH="$PATH:$GEM_HOME/bin"
  fi
fi
```

thanks!

**Comment by dgutov** [comment]
> Putting the configuration into ~/.bash_profile solved the problem!
> (trying the same thing with ~/.profile didn't work, maybe because bash zoo)

Yeah, IIRC it depends on the distro which file is actually used for the login shell.

**Comment by tjbrn** [comment]
Putting the configuration into `~/.bash_profile` solved the problem!
(trying the same thing with `~/.profile` didn't work, maybe because bash zoo)

So, for someone, as me, that doesn't uses rvm/rbenv, just put this code into your ~/.bash_profile and things should just works!
```
# "gem install" without sudo
if which ruby &>/dev/null && which gem &>/dev/null; then
  export GEM_HOME="$(ruby -rubygems -e 'puts Gem.user_dir')"
  if [[ ! "$PATH" == *$GEM_HOME/bin* ]]; then
    export PATH="$PATH:$GEM_HOME/bin"
  fi
fi
```

thanks!
