### ISSUE TITLE
docs say describe-packages will list commands, but it doesn't

### ISSUE THREAD

**Issue by bretweinraub** [dgutov/robe#111]
Project README says

    To see the available commands, type M-x describe-package RET robe RET.

For me, in emacs-25.3 installed from brew, produces:

    robe is a dependency package.

     Status: Installed in ‘robe-20170611.1755/’ (unsigned).
     Version: 20170611.1755
     Summary: Code navigation, documentation lookup and completion for Ruby
     Requires: inf-ruby-2.5.1, emacs-24.4
     Homepage: https://github.com/dgutov/robe
     Keywords: ruby convenience rails 
     Other versions: 20170611.1755 (melpa).

So it seems that the docs are in error?   

Although I drill into the lisp code, I can see

;;  - M-. to jump to the definition
;;  - M-, to jump back
;;  - C-c C-d to see the documentation
;;  - C-c C-k to refresh Rails environment
;;  - C-M-i to complete the symbol at point

**Comment by dgutov** [comment]
Which package repository did you install it from?

When you type `M-x describe-package RET robe RET`, which URL does Emacs contact? It should be in the messages buffer.

**Comment by bretweinraub** [comment]
Installed via cask:

.emacs.d/.cask/25.3/elpa/robe-20170611.1755

**Comment by dgutov** [comment]
Could you try installing it in the normal fashion?

**Comment by bretweinraub** [comment]
yup, that fixed it.   Thanks!

**Comment by dgutov** [comment]
Very good.

Maybe if you can reproduce the problem consistently, you should report it to Cask?

**Comment by bretweinraub** [comment]
A good idea.   I set Cask aside for the moment though.   It's not so clear to me what I get over the regular ELPA/MELPA package management.
