### ISSUE TITLE
company-robe: Symbol’s function definition is void: prefix

### ISSUE THREAD

**Issue by ckruse** [dgutov/robe#112]
Hi,

when trying to use `company-robe` I get the following error:

~~~
Company backend ’company-robe’ could not be initialized:
Symbol’s function definition is void: prefix
~~~

I installed `company` using `use-package`:

~~~elisp
(use-package robe
  :ensure t
  :commands robe-mode
  :after inf-ruby company
  :init
  (add-hook 'ruby-mode-hook 'robe-mode)
  (eval-after-load 'company
    '(push 'company-robe company-backends)))
~~~

Am I doing something wrong?

Best regards,  
 CK

**Comment by dgutov** [comment]
Hey!

Not sure why nobody encountered this before. This should take care of it.

Please reinstall and try it out when MELPA build the new commit.

**Comment by ckruse** [comment]
Works like a charm now, thanks!
