### ISSUE TITLE
Robe hangs attempting tls connection to server?

### ISSUE THREAD

**Issue by ddoherty03** [dgutov/robe#113]
I am running Emacs 25.1.1 (using spacemacs) and a melpa robe version robe-20171116.1249.

When I attempt to do a `(robe-jump)`, emacs hangs. If I set `toggle-debug-on-quit`, I get this stack trace:

    Debugger entered--Lisp error: (quit)
      gnutls-boot(#<process 127.0.0.1> gnutls-x509pki (:priority "NORMAL" :hostname "127.0.0.1" :loglevel 0 :min-prime-bits 256 :trustfiles ("/etc/ssl/certs/ca-certificates.crt") :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil))
      gnutls-negotiate(:process #<process 127.0.0.1> :type gnutls-x509pki :hostname "127.0.0.1")
      open-gnutls-stream("127.0.0.1" #<buffer  *url-http-temp*-983125> "127.0.0.1" 32888)
      network-stream-open-tls("127.0.0.1" #<buffer  *url-http-temp*-983125> "127.0.0.1" 32888 (:type tls :nowait t))
      open-network-stream("127.0.0.1" #<buffer  *url-http-temp*-983125> "127.0.0.1" 32888 :type tls :nowait t)
      url-open-stream("127.0.0.1" #<buffer  *url-http-temp*-983125> "127.0.0.1" 32888 nil)
      url-http-find-free-connection("127.0.0.1" 32888 nil)
      url-http([cl-struct-url "http" nil nil "127.0.0.1" 32888 "//ping/" nil nil t t t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
      url-retrieve-internal("http://127.0.0.1:32888//ping/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) t nil)
      url-retrieve("http://127.0.0.1:32888//ping/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil t nil)
      url-retrieve-synchronously("http://127.0.0.1:32888//ping/" t)
      robe-retrieve("http://127.0.0.1:32888//ping/")
      robe-request("ping")
      robe-start()
      robe-jump(nil)
      funcall-interactively(robe-jump nil)
      call-interactively(robe-jump)
      (progn (call-interactively handler))
      (condition-case nil (progn (call-interactively handler)) (error nil))
      (let ((handler (if (listp -handler) (car -handler) -handler)) (async (if (listp -handler) (progn (plist-get (cdr -handler) :async))))) (condition-case nil (progn (call-interactively handler)) (error nil)) (if (or (eq async t) (and (fboundp async) (funcall async)) (not (eq old-point (point))) (not (equal old-buffer (current-buffer)))) (progn (throw (quote done) t))))
      (while --dolist-tail-- (setq -handler (car --dolist-tail--)) (let ((handler (if (listp -handler) (car -handler) -handler)) (async (if (listp -handler) (progn (plist-get (cdr -handler) :async))))) (condition-case nil (progn (call-interactively handler)) (error nil)) (if (or (eq async t) (and (fboundp async) (funcall async)) (not (eq old-point (point))) (not (equal old-buffer (current-buffer)))) (progn (throw (quote done) t)))) (setq --dolist-tail-- (cdr --dolist-tail--)))
      (let ((--dolist-tail-- spacemacs-jump-handlers) -handler) (while --dolist-tail-- (setq -handler (car --dolist-tail--)) (let ((handler (if (listp -handler) (car -handler) -handler)) (async (if (listp -handler) (progn (plist-get ... :async))))) (condition-case nil (progn (call-interactively handler)) (error nil)) (if (or (eq async t) (and (fboundp async) (funcall async)) (not (eq old-point (point))) (not (equal old-buffer (current-buffer)))) (progn (throw (quote done) t)))) (setq --dolist-tail-- (cdr --dolist-tail--))))
      (let ((old-buffer (current-buffer)) (old-point (point))) (let ((--dolist-tail-- spacemacs-jump-handlers) -handler) (while --dolist-tail-- (setq -handler (car --dolist-tail--)) (let ((handler (if (listp -handler) (car -handler) -handler)) (async (if (listp -handler) (progn ...)))) (condition-case nil (progn (call-interactively handler)) (error nil)) (if (or (eq async t) (and (fboundp async) (funcall async)) (not (eq old-point ...)) (not (equal old-buffer ...))) (progn (throw (quote done) t)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
      (catch (quote done) (let ((old-buffer (current-buffer)) (old-point (point))) (let ((--dolist-tail-- spacemacs-jump-handlers) -handler) (while --dolist-tail-- (setq -handler (car --dolist-tail--)) (let ((handler (if ... ... -handler)) (async (if ... ...))) (condition-case nil (progn (call-interactively handler)) (error nil)) (if (or (eq async t) (and ... ...) (not ...) (not ...)) (progn (throw ... t)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (message "No jump handler was able to find this symbol."))
      spacemacs/jump-to-definition()
      funcall-interactively(spacemacs/jump-to-definition)
      call-interactively(spacemacs/jump-to-definition nil nil)
      command-execute(spacemacs/jump-to-definition)

Looks like its trying to negotiate a TLS-secured connection to the robe server,
and the server is hanging.

Can you see anything I'm doing wrong?

**Comment by dgutov** [comment]
Hi! 

Any chance you can try reproducing this with base Emacs?

**Comment by dgutov** [comment]
Do you have any proxy set up, maybe?

**Comment by ddoherty03** [comment]
Dmitry,

I have been unable to reproduce the error booting to a pretty bare emacs.  Must be something deep.

**Comment by ddoherty03** [comment]
Oh, and I have no proxy set up.

**Comment by dgutov** [comment]
Try asking on Spacemacs's gittter channel, then. And/or bisecting your config.

**Comment by ddoherty03** [comment]
Thanks, Dmitry.  I'll report back if I figure it out.

Cheers.

**Comment by ddoherty03** [comment]
Hmm.  After emacs restart, suddenly not hanging.  Close this.  Must have been cosmic rays.

**Comment by dgutov** [comment]
OK. You could close it yourself, actually.
