### ISSUE TITLE
choosing 'yes' after "No Ruby console running. Launch automatically?" results in "No matching directory found"

### ISSUE THREAD

**Issue by bolandross** [dgutov/robe#114]
Emacs 25.3
robe 0.7.7
inf-ruby 20180309.433

Getting this behavior after running `robe-start`

For testing I was just using a little HelloWorld script in a single .rb file.

**Comment by dgutov** [comment]
Your project doesn't have any of the usual markers, then. Like `Gemfile`, `.zeus.lock`, `*.gemspec` or `config.ru`.

**Comment by bolandross** [comment]
Thanks for your quick response, Dmitry.

I created a Gemfile in the folder, installed the bundler gem and tried it again.
Ruby is installed and managed via rbenv.
Now I am getting the error message:

`Searching for program: No such file or directory, bundle`

What would be the next steps to solve the issue?

**Comment by dgutov** [comment]
`gem install bundler`. That's like Ruby Basics 101.

If that's giving you trouble, I'm afraid trying Robe might be more hassle for you than it's worth. It's definitely not polished enough for less-experienced users (no offense implied).

**Comment by bolandross** [comment]
As described, I installed the gem and it works fine in the Terminal, that's why I was wondering about the error message in emacs.

The error message seems to only appear in the macOS-GUI version of emacs, though. When I run CLI emacs inside of bash Terminal/iTerm2, no error message appears.

But even there, after responding with "yes", it seems to run pry and just freezes emacs there.

(Pry version 0.11.3 on Ruby 2.5.0)

I guess it's as you said: The whole thing seems to be much more complex than I imagined. I am new to emacs and just wanted to give this package a try. Since the displayed error messages weren't helpful at all, I thought I might get some help here.

No offense taken, I wish you good luck with developing this package further.

**Comment by dgutov** [comment]
> I installed the gem and it works fine in the Terminal, that's why I was wondering about the error message in emacs

In that case, the problem is likely with rbenv integration, or the lack thereof (Emacs uses wrong version of Ruby). The exact solution depends on your OS. I just put rbenv init script into `~/.profile`.

**Comment by rprimus** [comment]
Tue Apr 10 18:59:11 BST 2018

@bolandross - see if https://github.com/dgutov/robe/issues/110#issuecomment-342627774 helps.

I've just installed `robe` and ran into a similar problem.   `robe-start` calls `inf-ruby-console-auto` which looks for the standard files @dgutov mentioned in [comment](https://github.com/dgutov/robe/issues/114#issuecomment-379334309) above.

The simplest solution is to manually open up a console (C-c C-s) and then run `robe-start` - the console will be running `irb`.

Creating a (non-required) `Gemfile` with `pry` and `pry-doc` allowed `robe-start` to run - the console will be `pry`.

**Comment by dgutov** [comment]
> open up a console (C-c C-s) and then run robe-start - the console will be running irb

In that case, the console won't have the project code loaded, and completion and code navigation will work so-so (unless you load the files manually).

**Comment by rprimus** [comment]
On Tue, Apr 10, 2018 at 01:12:25PM -0700, Dmitry Gutov wrote:
>> open up a console (C-c C-s) and then run robe-start - the console will be running irb
>
>In that case, the console won't have the project code loaded, and completion and code navigation will work so-so (unless you load the files manually).

Tue 10 Apr 2018 23:24:08 BST

The above is what worked for me working on a single file - trying to get 
completion working:

open ruby file -> inf-ruby -> rope-start

Didn't realise that, for a (properly laid out) project, all files are 
loaded.

-- 
-primus (Train yourself and be your own master.)
"First, solve the problem.  Then, write the code." - John Johnson
"Narrowness of experience leads to narrowness of imagination." - Rob Pike
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
