### ISSUE TITLE
Cannot load such file pry

### ISSUE THREAD

**Issue by oleksiivykhor** [dgutov/robe#118]
Is any approach to use `pry` globally for all projects on some ruby version? With `pry` in Gemfile ruby autocompletion is work fine (in Spacemacs) but without, I'm get the load error (after `robe-start`). I can't to add unnecessary gems to the Gemfile, so I looking for the solution to make `pry` globally available. I found suggestions to add `Pry.config.eager_load!` to `.pryrc` but thats not helps. I've add `pry` to the global gemset, but unsuccessful also.

**Comment by dgutov** [comment]
> I can't to add unnecessary gems to the Gemfile

I don't see why. Don't you have a `:development` group in Gemfile?

Anyway, I've searched around, and there seem to be two general approaches:

* https://github.com/janlelis/debundle.rb (didn't work for me during brief testing, but your experience might be different)

* Using a new second local-only Gemfile: https://github.com/bundler/bundler/issues/183#issuecomment-285773467 and advise `robe-start` with an around-function that sets the `BUNDLE_GEMFILE` environment variable.

**Comment by oleksiivykhor** [comment]
Thanks
