### ISSUE TITLE
Is there a way to show docs in completions popup/eldoc summary?

### ISSUE THREAD

**Issue by sandric** [dgutov/robe#119]
Hi, recently I started to wonder if there's a way to show `robe-doc` command output near completions list popup (I'm using company), or summary of method as eldoc below modeline, it works like a charm after I selected completion and place cursom on it, but I would love to see it during selection in company popup. Thx.

**Comment by dgutov** [comment]
You either press `C-h` to trigger the built in feature of company (you might have to select the exact class before the doc is shown), or install something like `company-quickhelp` and see the doc displayed automatically. In the latter case, though, it might automatically choose the class at random.
