### ISSUE TITLE
Autocompletion not working?

### ISSUE THREAD

**Issue by DanielViglione** [dgutov/robe#120]
I carefully traced my steps during the installation of this. I installed it through the MELPA repository.  I confirm it installed successfully:

~/.emacs.d/elpa$ ls -l | grep robe
drwxr-xr-x 3 dan dan 4096 Sep 24 17:13 robe-20190521.58
$ cat ~/.emacs | grep package-selected-packages
 '(package-selected-packages (quote (robe rvm projectile))))

I added the following to .emacs:

(add-hook 'ruby-mode-hook 'robe-mode)
(add-hook 'robe-mode-hook 'ac-robe-setup)

Also robe depends on the pry gem. Did the following:

# Gemfile
 gem 'pry'
 gem 'pry-doc', '>= 0.6.0'
$ bundle

C-x C-f and navigated to project
M-x, rvm-use and select ruby version and gemset
M-x rvm-activate-corresponding-ruby
M-x inf-ruby-console-auto 

So at this point, I have a rails console running. Now I open up a file in my project and run 'M-x robe start' and I notice in the console:

myproject :001 >  => "robe on 39715" 

But there is no autocompletion. I can do certain commands like M+x robe-jump and that works. But I get no autocompletion in the project or in the console that was started by robe. 

I am using ruby-2.4.7, Rails  4.2.8.rc1, if that helps.

**Comment by dgutov** [comment]
> ac-robe-setup

Are you using the `auto-complete` package?
