### ISSUE TITLE
Robe cannot autostart: "No matching directory found"

### ISSUE THREAD

**Issue by treymerkley** [dgutov/robe#125]
I'm using Emacs 26.3. When I try to run robe autostart, I get the above error. I'm on version 20200614.150 from MELPA.

What else do you need?

**Comment by dgutov** [comment]
Apparently `inf-ruby-console-auto` can't recognize your project, so it fails.

Some details about the project should help.

**Comment by treymerkley** [comment]
That would explain it. I'm not running it as a dedicated project at the moment, just testing out `ruby-jmeter`. It'll only work if there's a project?

**Comment by dgutov** [comment]
It need to know how to launch a REPL with the project loaded. See the README.

**Comment by treymerkley** [comment]
Can do. I'll read it more thoroughly and if I run into any issues I'll reopen.
