### ISSUE TITLE
Robe not working on Ruby 2.7.1

### ISSUE THREAD

**Issue by TulioMagnus** [dgutov/robe#126]
Does anyone have the same problem?
Rails console and server running ok.
![image](https://user-images.githubusercontent.com/12403762/87457718-3d986d80-c5df-11ea-93ae-0c89343fe104.png)

**Comment by dgutov** [comment]
I imagine neither `M-x inf-ruby-console-auto` nor `(run-ruby "rails console development")" work well for you?

**Comment by dgutov** [comment]
Try creating an `.irbrc` file in the root of the project with this line inside: `IRB.conf[:USE_MULTILINE] = false`.

Also see https://github.com/ruby/irb/issues/113.

**Comment by dgutov** [comment]
Or you can update to the latest `inf-ruby` and try again. As long as your version of Rails is < 5 or >= 5.1.4.
