### ISSUE TITLE
robe make emacs freeze on 27 on large projects

### ISSUE THREAD

**Issue by otavioschwanck** [dgutov/robe#127]
i had to stop using robe-start because of this bug.  When complation is about to show, the emacs freeze sometimes (+/- 30m of use).  The  problem is probabily because of json library

**Comment by dgutov** [comment]
Is that with the latest version?

What do you mean by Emacs freeze? Does it stop responding to input? Not even after `C-g C-g C-g`?

**Comment by otavioschwanck** [comment]
@dgutov i'm using last version of robe.  

Emacs:

➜  ~ emacs --version
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

It completely frozen, i've to close with xkill and open again.

OS: Arch Linux.

Tested on Ubuntu, i compiled the emacs 27 and the same error happens.

On emacs 26 the freeze dont occurs.

**Comment by dgutov** [comment]
You can try `kill -SIGUSR2 <pid>` to try to break it out of whatever loop it is in into a debugger. And then post the backtrace it shows you, if that happens.

`<pid>` is the identifier of the Emacs' process.

**Comment by otavioschwanck** [comment]
i'll try.

**Comment by dgutov** [comment]
Thank you.If that doesn't help, there things you could try with gdb.02:02, August 14, 2020, "Otávio Schwanck dos Santos" <notifications@github.com>:
i'll try.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Dmitry Gutov

**Comment by dgutov** [comment]
BTW, what do you mean by 

> When complation is about to show

?

What "compilation"?

**Comment by otavioschwanck** [comment]
> BTW, what do you mean by
> 
> > When complation is about to show
> 
> ?
> 
> What "compilation"?

complation = company auto complete.

I did the kill -SIGUSR2 and here is the results:
![image](https://user-images.githubusercontent.com/9551316/90548741-c9b02e80-e163-11ea-9fb1-a800754fa6ff.png)

@dgutov

**Comment by dgutov** [comment]
> complation = company auto complete

Ah, you mean completion.

> I did the kill -SIGUSR2 and here is the results

Thank you. So this happens during the HTTP request. Then this probably means the JSON parser is not at fault. It just makes some things faster, which changes the timing of operations.

> if i try to autocomplete again, this crash occurs every time

You mean a freeze, right?

There are two avenues for research.

First: does the Ruby process look frozen, when this happens? Is its CPU usage at 100%? If so, you can try these instructions: https://github.com/dgutov/robe/issues/121#issuecomment-643496704

Second: if you start that session in advance using GDB (`gdb emacs`), when it freezes, you can press `C-c` to break out into the debugger. And then use the `backtrace` command to print the current C-level backtrace. Perhaps it will grant us some insight.

**Comment by dgutov** [comment]
Also: please double-check the version of `robe` that you're using and post it here.

**Comment by otavioschwanck** [comment]
> You mean a freeze, right?

Yes

> First: does the Ruby process look frozen, when this happens? Is its CPU usage at 100%? If so, you can try these instructions: #121 (comment)

I don't pay attention to this, but my computer seems fine, i do not see any lag at all

> Second: if you start that session in advance using GDB (gdb emacs), when it freezes, you can press C-c to break out into the debugger. And then use the backtrace command to print the current C-level backtrace. Perhaps it will grant us some insight.

What is GDB ? i don't have it installed on my pc.

> Also: please double-check the version of robe that you're using and post it here.

0.8.2

**Comment by dgutov** [comment]
> I don't pay attention to this, but my computer seems fine, i do not see any lag at all

Ruby is single-threaded, so you probably do not notice, with modern processors being multi-core.

> What is GDB ? i don't have it installed on my pc.

https://www.gnu.org/software/gdb/

It's "the gcc debugger", basically.

But first...

> 0.8.2

...upgrade to 0.8.3, please. It has been released about a month ago: https://github.com/dgutov/robe/releases/tag/0.8.3

And it contains a fix for a problem very similar to what you are describing.

**Comment by otavioschwanck** [comment]
> The instructions are here: [#121 (comment)](https://github.com/dgutov/robe/issues/121#issuecomment-643496704)

Next time i'll do.

**Comment by dgutov** [comment]
Hi Otavio,

Any luck?
