### ISSUE TITLE
Non-string path in LOAD_PATH

### ISSUE THREAD

**Issue by link0ff** [dgutov/robe#128]
When initialization uses such code to add load_path

```ruby
config.autoload_paths << Rails.root.join('lib')
```

then among paths that are strings, `$LOAD_PATH` contains a non-string path such as `#<Pathname:./lib>`

In this case `(robe-request "load_path")` in `robe-start` gets `{"path":"./lib"}` and returns `("/path/as/string1" "/path/as/string2" ((path . "./lib"))` among string paths.

Then `file-name-as-directory` fails in `robe-start` with

```
Debugger entered--Lisp error: (wrong-type-argument stringp ((path . "./lib")))
  file-name-as-directory(((path . "./lib")))
  mapcar(file-name-as-directory
```

**Comment by dgutov** [comment]
Hi! Thanks for the report.

The fix should be simple, but how do I repro? So far I've tried

```rb
Rails.application.config.autoload_paths += [Rails.root.join('libbb')]
```

in a sample Rails 5 application, and that value is just not added to `$LOAD_PATH`. Modifying load path at runtime looks prohibited too: `NameError ($LOAD_PATH is a read-only variable)`.

Which versions of Rails and Ruby are you using?

**Comment by link0ff** [comment]
Actually it's Rails 4 - a legacy app that soon will be upgraded to Rails 6 :-)

**Comment by dgutov** [comment]
Ok then, I'll do a test with the closest approximation. :+1:
