### ISSUE TITLE
Get search failed message when run robe-jump.

### ISSUE THREAD

**Issue by zw963** [dgutov/robe#132]
I get following error message when run `robe-jump`, but, file jump to target file successful.

ad-Advice-re-search-forward: Search failed: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_>\\|^[ 	]*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_> *=[^=>]" 36 40 (fontified t font-lock-face font-lock-type-face) 45 56 (fontified t font-lock-face font-lock-type-face) 61 70 (fontified t font-lock-face font-lock-type-face) 75 79 (fontified t font-lock-face font-lock-type-face) 99 103 (fontified t font-lock-face font-lock-type-face) 108 119 (fontified t font-lock-face font-lock-type-face) 124 133 (fontified t font-lock-face font-lock-type-face) 138 142 (fontified t font-lock-face font-lock-type-face))

You can check source code from my git repo.

https://github.com/zw963/marketbet_crawler/tree/test_robe

It should be works if you run from Procfile use procodile or foreman.

Thank you.

**Comment by zw963** [comment]
BTW, if you want start server, you must set env like this:

```sh
export APP_SESSION_SECRET="909f017cc94c96f8a1aff843d95920485376f4c997143cc3c39ca945c883ec88e310a2177a69b8b714d22af1b5fd7864833568b6bf93fc3bc811bcf6e112"
export DEVELOPMENT_DATABASE_URL="sqlite://db/files/marketbet_crawler_development.db"
```

**Comment by dgutov** [comment]
Hi!

Which file did you get this error in?

`robe-jump` must have jumped to a file, but then showed this error because it couldn't find the constant.

**Comment by zw963** [comment]
Sorry, i run it when my cursor on config/application.rb

![image](https://user-images.githubusercontent.com/549126/128893174-b4a419d8-8bd4-410d-afc1-a116cba67d2b.png)

It skip to following correct gem file successful, e.g.
 
~/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/roda-sprockets-1.0.1/lib/roda/plugins/sprockets.rb

But, still get this error message. following is backtrace.

Debugger entered--Lisp error: (search-failed #("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (font-lock-face font-lock-type-face fontified t) 45 56 (font-lock-face font-lock-type-face fontified t) 61 70 (font-lock-face font-lock-type-face fontified t) 75 79 (font-lock-face font-lock-type-face fontified t) 99 103 (font-lock-face font-lock-type-face fontified t) 108 119 (font-lock-face font-lock-type-face fontified t) 124 133 (font-lock-face font-lock-type-face fontified t) 138 142 (font-lock-face font-lock-type-face fontified t)))
  #<subr re-search-forward>(#("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (font-lock-face font-lock-type-face fontified t) 45 56 (font-lock-face font-lock-type-face fontified t) 61 70 (font-lock-face font-lock-type-face fontified t) 75 79 (font-lock-face font-lock-type-face fontified t) 99 103 (font-lock-face font-lock-type-face fontified t) 108 119 (font-lock-face font-lock-type-face fontified t) 124 133 (font-lock-face font-lock-type-face fontified t) 138 142 (font-lock-face font-lock-type-face fontified t)) nil nil nil)
  ad-Advice-re-search-forward(#<subr re-search-forward> #("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (font-lock-face font-lock-type-face fontified t) 45 56 (font-lock-face font-lock-type-face fontified t) 61 70 (font-lock-face font-lock-type-face fontified t) 75 79 (font-lock-face font-lock-type-face fontified t) 99 103 (font-lock-face font-lock-type-face fontified t) 108 119 (font-lock-face font-lock-type-face fontified t) 124 133 (font-lock-face font-lock-type-face fontified t) 138 142 (font-lock-face font-lock-type-face fontified t)))
  apply(ad-Advice-re-search-forward #<subr re-search-forward> #("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (font-lock-face font-lock-type-face fontified t) 45 56 (font-lock-face font-lock-type-face fontified t) 61 70 (font-lock-face font-lock-type-face fontified t) 75 79 (font-lock-face font-lock-type-face fontified t) 99 103 (font-lock-face font-lock-type-face fontified t) 108 119 (font-lock-face font-lock-type-face fontified t) 124 133 (font-lock-face font-lock-type-face fontified t) 138 142 (font-lock-face font-lock-type-face fontified t)))
  re-search-forward(#("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (font-lock-face font-lock-type-face fontified t) 45 56 (font-lock-face font-lock-type-face fontified t) 61 70 (font-lock-face font-lock-type-face fontified t) 75 79 (font-lock-face font-lock-type-face fontified t) 99 103 (font-lock-face font-lock-type-face fontified t) 108 119 (font-lock-face font-lock-type-face fontified t) 124 133 (font-lock-face font-lock-type-face fontified t) 138 142 (font-lock-face font-lock-type-face fontified t)))
  robe-jump-to-module(#("Roda::RodaPlugins::Sprockets::Task" 0 4 (font-lock-face font-lock-type-face fontified t) 4 6 (font-lock-face enh-ruby-op-face fontified t) 6 17 (font-lock-face font-lock-type-face fontified t) 17 19 (font-lock-face enh-ruby-op-face fontified t) 19 28 (font-lock-face font-lock-type-face fontified t) 28 30 (font-lock-face enh-ruby-op-face fontified t) 30 34 (font-lock-face font-lock-type-face fontified t)))
  robe-jump(nil)
  funcall-interactively(robe-jump nil)
  call-interactively(robe-jump nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fdcbaaf68b3>)(robe-jump nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fdcbaaf68b3>) robe-jump)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fdcbaaf68b3>) robe-jump)
  command-execute(robe-jump)

**Comment by dgutov** [comment]
Thanks for the detail. But please post code using Markdown's "code block" syntax next time: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

This operation seems to work fine here (though I haven't tried running the project itself so far).

Could you try the scenario with the built-in `ruby-mode` rather than `enh-ruby-mode`, to eliminate at least this suspect?

Your backtrace mentions `ad-Advice-re-search-forward`. What kind of advice do you have on `re-search-forward`? Can you try removing it as well?

**Comment by zw963** [comment]
> Could you try the scenario with the built-in ruby-mode rather than enh-ruby-mode, to eliminate at least this suspect?

> Your backtrace mentions ad-Advice-re-search-forward. What kind of advice do you have on re-search-forward? Can you try removing it as well?

It come from fancy-narrow, i diable it now.

following is new backtrace.
```
Debugger entered--Lisp error: (search-failed #("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (face font-lock-type-face fontified t) 45 56 (face font-lock-type-face fontified t) 61 70 (face font-lock-type-face fontified t) 75 79 (face font-lock-type-face fontified t) 99 103 (face font-lock-type-face fontified t) 108 119 (face font-lock-type-face fontified t) 124 133 (face font-lock-type-face fontified t) 138 142 (face font-lock-type-face fontified t)))
  re-search-forward(#("^[ \11]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaP..." 36 40 (face font-lock-type-face fontified t) 45 56 (face font-lock-type-face fontified t) 61 70 (face font-lock-type-face fontified t) 75 79 (face font-lock-type-face fontified t) 99 103 (face font-lock-type-face fontified t) 108 119 (face font-lock-type-face fontified t) 124 133 (face font-lock-type-face fontified t) 138 142 (face font-lock-type-face fontified t)))
  robe-jump-to-module(#("Roda::RodaPlugins::Sprockets::Task" 0 4 (face font-lock-type-face fontified t) 4 6 (fontified t) 6 17 (face font-lock-type-face fontified t) 17 19 (fontified t) 19 28 (face font-lock-type-face fontified t) 28 30 (fontified t) 30 34 (face font-lock-type-face fontified t)))
  robe-jump(nil)
  funcall-interactively(robe-jump nil)
  call-interactively(robe-jump nil nil)
  command-execute(robe-jump)
```

**Comment by dgutov** [comment]
Thanks. But I still don't see anything that can explain the behavior in that backtrace.

Which Emacs version are you using? Which version of Robe?

Can you verify which search is failing? The exact regexp string, and in which file it fails? Is it https://github.com/hmdne/roda-sprockets/blob/v1.0.1/lib/roda/plugins/sprockets_task.rb?

You can step through `robe-jump-to-module` with Edebug to evaluate it, or just apply this patch:

```diff
diff --git a/robe.el b/robe.el
index 276ff2c..d6d96a4 100644
--- a/robe.el
+++ b/robe.el
@@ -529,11 +529,13 @@ If invoked with a prefix or no symbol at point, delegate to `robe-ask'."
                                             concat "\\(")
                                    (mapconcat #'identity nesting "::\\)?")
                                    "\\_>"))
+             (full-re (concat "^[ \t]*\\(class\\|module\\) +.*"
+                              nesting-re
+                              "\\|"
+                              "^[ \t]*" nesting-re " *=[^=>]"))
              case-fold-search)
-        (re-search-forward (concat "^[ \t]*\\(class\\|module\\) +.*"
-                                   nesting-re
-                                   "\\|"
-                                   "^[ \t]*" nesting-re " *=[^=>]")))
+        (message "re: %s" (pp-to-string full-re))
+        (re-search-forward full-re))
       (back-to-indentation))))
 
 (defun robe-to-abbr-paths (list)
```

and then look for it in `*Messages*`. It looks like

```el
re: #("^[ 	]*\\(class\\|module\\) +.*\\_<Task\\_>\\|^[ 	]*\\_<Task\\_> *=[^=>]" 30 34
  (fontified t face font-lock-type-face)
  48 52
  (fontified t face font-lock-type-face))
```

over here.

**Comment by zw963** [comment]
Sorry for confusing, i use minimum config to try reproduce this, but this issue never happen when cursor on `Sprockets`, it jump to `~.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/roda-sprockets-1.0.1/lib/roda/plugins/sprockets.rb` (assume you RVM), line 7, as following screenshot. this is expected behavior.


![image](https://user-images.githubusercontent.com/549126/129358595-b9c925bd-e0e3-4acd-9993-562ec9e4332a.png)

 please give me some time to find out which package(or config) broken this.
i will report here after i find it.


> Does `(goto-char (point-min))` go to the beginning of the file in that buffer?

Yes, when issue happen, i can reproduce this.

In fact, i still can reproduce this (goto point-min) when cursor on `Task` in `Roda::RodaPlugins::Sprockets::Task`, i guess cause this because robe find the wrong file.

It should be skip to ~/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/roda-sprockets-1.0.1/lib/roda/plugins/```sprockets_task.rb```, but it skip to /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/roda-sprockets-1.0.1/lib/roda/plugins/```sprockets.rb```

Following is output:

```
re: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_>\\|^[ 	]*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_> *=[^=>]" 36 40
  (fontified t face font-lock-type-face)
  45 56
  (fontified t face font-lock-type-face)
  61 70
  (fontified t face font-lock-type-face)
  75 79
  (fontified t face font-lock-type-face)
  99 103
  (fontified t face font-lock-type-face)
  108 119
  (fontified t face font-lock-type-face)
  124 133
  (fontified t face font-lock-type-face)
  138 142
  (fontified t face font-lock-type-face))

robe-jump-to-module: Search failed: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_>\\|^[ 	]*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_> *=[^=>]" 36 40 (fontified t face font-lock-type-face) 45 56 (fontified t face font-lock-type-face) 61 70 (fontified t face font-lock-type-face) 75 79 (fontified t face font-lock-type-face) 99 103 (fontified t face font-lock-type-face) 108 119 (fontified t face font-lock-type-face) 124 133 (fontified t face font-lock-type-face) 138 142 (fontified t face font-lock-type-face))
Mark set
```

**Comment by dgutov** [comment]
> i guess cause this because robe find the wrong file

All right, that makes sense, thanks. I'll look into it more tonight.

**Comment by dgutov** [comment]
But also if you wanted to actually jump to `Sprockets` when the cursor it on that word, but the full text is `Sprockets::Task`, switch to `ruby-mode` first: it's a problem with `enh-ruby-mode`'s syntax table.

**Comment by zw963** [comment]
> But also if you wanted to actually jump to `Sprockets` when the cursor is on that word, but the full text is `Sprockets::Task`, switch to `ruby-mode` first: it's a problem with `enh-ruby-mode`'s syntax table.

Yes, i test it with ruby-mode only after you told me do that, anyway, i consider there exists another factor cause this, i use many emacs package (as like most of emacser), i need use dichotomy to find out which cause this, i will report soon.

**Comment by zw963** [comment]
@dgutov , sorry for confusing again, it my fault.

i double test, yes, this issue only happen on enh-ruby-mode.

Following is debug info:

```
re: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_>\\|^[ 	]*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_> *=[^=>]" 36 40
  (fontified t font-lock-face font-lock-type-face)
  45 56
  (fontified t font-lock-face font-lock-type-face)
  61 70
  (fontified t font-lock-face font-lock-type-face)
  75 79
  (fontified t font-lock-face font-lock-type-face)
  99 103
  (fontified t font-lock-face font-lock-type-face)
  108 119
  (fontified t font-lock-face font-lock-type-face)
  124 133
  (fontified t font-lock-face font-lock-type-face)
  138 142
  (fontified t font-lock-face font-lock-type-face))
 ```
 

so, i saw you open a issue to enh-ruby-mode, please check if same reason cause above error, thank you.

**Comment by dgutov** [comment]
> i double test, yes, this issue only happen on enh-ruby-mode

Sure.

But what happens if you move point to the word `Task` and press `M-.`?

I think you should see the same error. Don't you?

**Comment by zw963** [comment]
I test with the the hack from https://github.com/zenspider/enhanced-ruby-mode/issues/182#issuecomment-898582249, after apply it,  point on the word `Sprockets` works now on enh-ruby-mode, following is debug info.

```
re: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets\\_>\\|^[ 	]*\\_<\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets\\_> *=[^=>]" 34 38
  (fontified t font-lock-face font-lock-type-face)
  43 54
  (fontified t font-lock-face font-lock-type-face)
  59 68
  (fontified t font-lock-face font-lock-type-face)
  86 90
  (fontified t font-lock-face font-lock-type-face)
  95 106
  (fontified t font-lock-face font-lock-type-face)
  111 120
  (fontified t font-lock-face font-lock-type-face))
```




> But what happens if you move point to the word `Task` and press `M-.`?
> 
> I think you should see the same error. Don't you?

Yes, above hack not resolve  the issue when point to the word `Task`.

Following is debug info.

```
re: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_>\\|^[ 	]*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_> *=[^=>]" 36 40
  (fontified t font-lock-face font-lock-type-face)
  45 56
  (fontified t font-lock-face font-lock-type-face)
  61 70
  (fontified t font-lock-face font-lock-type-face)
  75 79
  (fontified t font-lock-face font-lock-type-face)
  99 103
  (fontified t font-lock-face font-lock-type-face)
  108 119
  (fontified t font-lock-face font-lock-type-face)
  124 133
  (fontified t font-lock-face font-lock-type-face)
  138 142
  (fontified t font-lock-face font-lock-type-face))

robe-jump-to-module: Search failed: #("^[ 	]*\\(class\\|module\\) +.*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_>\\|^[ 	]*\\_<\\(\\(\\(Roda::\\)?RodaPlugins::\\)?Sprockets::\\)?Task\\_> *=[^=>]" 36 40 (fontified t font-lock-face font-lock-type-face) 45 56 (fontified t font-lock-face font-lock-type-face) 61 70 (fontified t font-lock-face font-lock-type-face) 75 79 (fontified t font-lock-face font-lock-type-face) 99 103 (fontified t font-lock-face font-lock-type-face) 108 119 (fontified t font-lock-face font-lock-type-face) 124 133 (fontified t font-lock-face font-lock-type-face) 138 142 (fontified t font-lock-face font-lock-type-face))
```

**Comment by dgutov** [comment]
Okay, now, could you step-by-step explain how you launch Robe with this application?

I managed to do so with a custom invocation `(run-ruby "bin/irb")`, but it wasn't trivial/automatic, and in the end the feature worked, however (no error after jumping to `Task`). There is a certain clutch in its implementation, but it would be much easier for me to decide what to do with it with a concrete example.

Do you use Ruby 3 (as the backtraces seem to indicate)? But Gemfile doesn't include `webrick`. Don't you get `cannot load such file -- webrick` when trying to load Robe?

**Comment by zw963** [comment]
> Okay, now, could you step-by-step explain how you launch Robe with this application?

Because this is only for debug, so, i add webrick into $LOAD_PATH use `RUBYLIB` envs,  e.g.
my shell $RUBYLIB is: ``~/Dropbox/common/ruby/lib:....``, webrick gem file is there, like this.

```
~/Dropbox/common/ruby/lib/webrick.rb
~/Dropbox/common/ruby/lib/webrick/ ....
```





 

and use it directly.

> Do you use Ruby 3 (as the backtraces seem to indicate)?

Yes, I add webrick back to Gemfile, add delete webrick from $LOAD_PATH, but still get same search failed message as before when use minimum config for `Task`.

![image](https://user-images.githubusercontent.com/549126/129433045-dd1073f7-3aa8-4f8d-b23d-6a7fa345c3f8.png)


you can check my ruby config here. https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/ruby_init.el

BTW:  those config suffix with `???_init.el` is my own config, will require package then config it in it.

**Comment by zw963** [comment]
BTW: what i said `minimum config` is emacs 27.2 + following 4 config only.
```el
(require 'enh-ruby-mode_init)
(require 'rvm_init)
(require 'inf-ruby_init)
(require 'robe-mode_init)
```
you can check those file at:
[enh-ruby-mode_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/enh-ruby-mode/enh-ruby-mode_init.el)
[rvm_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/rvm/rvm_init.el)
[inf-ruby_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/inf-ruby/inf-ruby_init.el)
[robe-mode_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/robe-mode/robe-mode_init.el)

the packages which relative to config is predownloaded on same folder as above config. 

And, I can reproduce this issue on ruby 2.7.2 + builtin webrick.

**Comment by dgutov** [comment]
All right, I can repro, thanks. Stay tuned.

**Comment by dgutov** [comment]
This should take care of the remaining issue (Emacs should say `Can't find the location` instead of jumping to `sprockets.rb`).

Why Task was not defined, and how to fix that, has already been discussed in the subsequent issue.

**Comment by zw963** [comment]
Cool, this fix works, not it report `Can't find the location` instead.
