### ISSUE TITLE
`Can't find the location` when try to search a class defined on current project. (but can in irb)

### ISSUE THREAD

**Issue by zw963** [dgutov/robe#133]
This issue happen on same project as my previous `Task` issue.

When try to look up the `RetrieveLatestInstitutions`  define in following code.

https://github.com/zw963/marketbet_crawler/blob/test_robe/app/app.rb#L63

![image](https://user-images.githubusercontent.com/549126/129727852-07e3b724-9c90-455c-be53-df33ca10a84a.png)

Get following error.

```
Robe connection established
robe-jump-to-module: Can’t find the location
```

this class defined on https://github.com/zw963/marketbet_crawler/blob/test_robe/app/services/retrieve_latest_institutions.rb#L1, but robe can't find it.

i guess this should be specify a app entry issue, because we have to load the entry environment before start irb session.
e.g.  if start irb from `bin/irb` instead irb directly,  that is.

```rb
#!/usr/bin/env ruby

require 'irb'
require_relative '../config/environment'

IRB.start(__FILE__)
```

We can access RetrieveLatestInstitutions class successful.

```sh
 ╰─ $ bin/irb
3.0.2 :001 > RetrieveLatestInstitutions
 => RetrieveLatestInstitutions 
```

 so, i guess (maybe i am wrong), this really issue is, how to tell robe to `require_relative '../config/environment'` before start irb session?  

--------

mininum config:

[enh-ruby-mode_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/enh-ruby-mode/enh-ruby-mode_init.el)
[rvm_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/rvm/rvm_init.el)
[inf-ruby_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/inf-ruby/inf-ruby_init.el)
[robe-mode_init](https://github.com/zw963/.emacs.d/blob/master/plugins/ruby/robe-mode/robe-mode_init.el)

Thank you.

**Comment by zw963** [comment]
After some research, i consider this maybe a issue about `inf-ruby.el`.

when when i start `inf-ruby-console-auto` manually, it not require my `config/environment.rb` automatically.

```sh
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
3.0.2 :001 > RetrieveLatestInstitutions
(irb):1:in `<main>': uninitialized constant RetrieveLatestInstitutions (NameError)
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli/console.rb:19:in `run'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli.rb:504:in `console'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/bundle:23:in `load'
	from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/bundle:23:in `<main>'
	from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/ruby_executable_hooks:22:in `eval'
	from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/ruby_executable_hooks:22:in `<main>'
3.0.2 :002 > 
```

so, for this general purpose roda project (no rails, no hanami), is there exists a general approach to let inf-ruby to require my `config/environment.rb` before start console?

Thank you.

**Comment by dgutov** [comment]
Short answer: add `racksh` to `Gemfile`. Then `inf-ruby-console-auto` will pick `inf-ruby-console-racksh`. racksh loads `config.ru`, which in turn loads your environment. This will also fix the problem with navigating to `Task` in the other issue.

Alternatively, as a quick solution, you can launch the console with `(run-ruby "bin/irb")` before calling `robe-start`.

Please keep #132 open, though. I think it's behavior (when constant is really not defined) is still faulty.

**Comment by dgutov** [comment]
You can also try `ln -s bin/irb bin/console`.

**Comment by zw963** [comment]
> You can also try `ln -s bin/irb bin/console`.

It works! haha,  i try it myself, and then, i saw your's reply.

>  This will also fix the problem with navigating to `Task` in the other issue.

Yes, this issue is fixed now, after create a bin/console, Cool.

In fact, i want to use `bin/console` this name when i start this project, but, i saw webrick offer `console` command, use same name, so i change to bin/irb, for avoid conflict ...

thank you very much for explain.

**Comment by zw963** [comment]
@dgutov , this is should not be consider as a issue, but, anyway, after i move those code into a rake task, it not work.

Please check [this](https://github.com/zw963/marketbet_crawler/blob/master/lib/tasks/assets.rake#L10-L16)

```rb
desc 'Clean assets'
  task :clean do
    require_relative '../../config/environment'
    require 'roda/plugins/sprockets_task'
    Roda::RodaPlugins::Sprockets::Task.define!(App)
    Rake::Task['assets:clean'].invoke
  end
```

because define rake task need App constant to be defined(which need load config/environment), but, many other rake task don't need, so, i wrap those code into a `task block`,  for this reason, search `Task` definition still not work, because i never run following code when start irb.

```rb
require 'roda/plugins/sprockets_task'
Roda::RodaPlugins::Sprockets::Task.define!(App)
```

Sure i can add those code back into `config/environemnt.rb`, but, it is not good, because those only for define rack task, not for app.

**Comment by dgutov** [comment]
You can add code loading the tasks to `bin/console`, or you can load the individual files manually with `C-c C-l`.

Or create a file called `.robe` and add such code there. Those are the main options, I think.
