### ISSUE TITLE
rspec docs

### ISSUE THREAD

**Issue by chalmagean** [dgutov/robe#19]
Hi, I've recently found robe and I'm trying to get the doc or source code for methods like `describe` or `expect` (from rspec) and I get `Method not found` or some unrelated classes. Am I missing something ? Do I need to configure it somehow ?

Thanks

**Comment by dgutov** [comment]
With 4e36a4725970588d55e1951d048a76aed61274c0, you can create a file named `.robe` in the root of the project and put `require 'rspec'` there.
