### ISSUE TITLE
very slow for single-letter completions

### ISSUE THREAD

**Issue by Silex** [dgutov/robe#29]
Hello,

I have `(setq company-minimum-prefix-length 1)` in my config.

Whenever I type `[].pus` then wait a little, the completion comes quickly (with push, push_bulk, push_inspect_key, etc). Then I press backspace twice and I have to wait around 10 seconds to get the `[].p` completions.

Same happens if I type `[].p` and then wait a little.

I guess this problem cannot be really solved, so my suggestion is to maybe turn the completion into something like "here is the list I have so far", which would be updated whenever new results come in.

At least make it asynchronous if you can :)

[EDIT] or... maybe just ignore it because minimum prefix length to 1 is probably a bit silly anyway? I'll set it to 2 and test the speed.

**Comment by dgutov** [comment]
Just did some measuring. For an empty prefix, I get about 17K completions, and that takes ~3.6 seconds in total.

Of that, ~800ms is spent collecting completions, ~900 serializing to JSON (as long as we just use the built-in JSON package), and the remaining time (1.9s?) on parsing JSON in Emacs.

For one-letter prefix, everything is an order of magnitude faster, though.

**Comment by dgutov** [comment]
@Silex You can try it again now. c9de1dad186086733ff77f426b28c0f7ab7e9e24 has evened out a particular pathological case.

**Comment by Silex** [comment]
@dgutov: I'll try, but I'm pretty swamped atm

**Comment by Silex** [comment]
Ok, I *finally* had time to test and yes, the problem is gone.

Thank you!
