### ISSUE TITLE
cannot run robe-rails-refresh

### ISSUE THREAD

**Issue by rranelli** [dgutov/robe#32]
Hi,

I'm starting to use robe for rails development (read: I'm a newb) and now, all of a sudden, it doesn't work. When I run 'robe-rails-refresh' I get:

```
irb(main):002:0> E, [2014-06-06T19:59:35.875500 #31185] ERROR -- : Request failed: /rails_refresh/. Please file an issue.
E, [2014-06-06T19:59:35.875573 #31185] ERROR -- : uninitialized constant Robe::Sash::ActionDispatch
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe/sash.rb:171:in `rails_refresh'
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe/sash.rb:182:in `public_send'
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe/sash.rb:182:in `call'
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe/server.rb:40:in `block in start'
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe/server.rb:28:in `loop'
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe/server.rb:28:in `start'
/home/renanranelli/.emacs.d/elpa/robe-20140401.1339/lib/robe.rb:18:in `block in start'
```

I'm using rbenv and everything seens to work fine on emacs (e.g. rspec-mode) so I don't think it's an issue with that.

Also, when I open emacs shell and type `bundle exec rails console` and then `MyModel.new`` I receive:

```
WARNING: terminal is not fully functional
-  (press RETURN)
```

I have read issue #9 but since my `inf-ruby` shows `=> "robe on"` I think that's not the same issue.

Any ideas ?

**Comment by stardiviner** [comment]
I got this same issue now.

```
head :005 > E, [2015-02-24T09:31:34.598727 #4893] ERROR -- : Request failed: /rails_refresh/. Please file an issue.
E, [2015-02-24T09:31:34.598779 #4893] ERROR -- : uninitialized constant Robe::Sash::ActionDispatch
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe/sash.rb:165:in `rails_refresh'
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe/sash.rb:176:in `public_send'
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe/sash.rb:176:in `call'
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe/server.rb:40:in `block in start'
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe/server.rb:28:in `loop'
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe/server.rb:28:in `start'
/home/stardiviner/.emacs.d/el-get/robe-mode/lib/robe.rb:18:in `block in start'
```

**Comment by dgutov** [comment]
@stardiviner Do you use Rails? What does `(inf-ruby-console-rails-p)` return?

**Comment by dgutov** [comment]
...if you run it in the application root.

**Comment by stardiviner** [comment]
I get `t` when run command `(inf-ruby-console-rails-p)` in Rails app root.
And I get `nil` when run command `(inf-ruby-console-rails-p)` *not* in Rails app root.

**Comment by stardiviner** [comment]
I get `t` when run command `(inf-ruby-console-rails-p)` in Rails app root.
And I get `nil` when run command `(inf-ruby-console-rails-p)` *not* in Rails app root.

**Comment by stardiviner** [comment]
@dgutov Do you have any update on this issue?

**Comment by dgutov** [comment]
@stardiviner No progress. How do I reproduce it?

If you create a new Rails project, do you see the problem there as well?

**Comment by stardiviner** [comment]
@dgutov yes, see the problem in a new Rails project.
Rails version: `Rails 4.2.1`
Ruby version: `ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]`
Emacs version: `GNU Emacs 25.0.50.1`
irb version: `irb 0.9.6(09/06/30)`
Bunder version `1.9.8`

**Comment by dgutov** [comment]
Works for me, with Ruby 2.2.0 and Rails 4.2.1 as well. Same Emacs and `irb`, Bundler 1.9.4 or 1.9.9.

You should write step-by-step how you get to the error. The exact way you create a new project (is it `rails new ...` followed by `bundle install`?), and what steps you perform after launching Emacs.

**Comment by stardiviner** [comment]
# error
I know why have this error now:
I configure inf-ruby and robe-mode like this:
```el
(with-eval-after-load 'inf-ruby
  (unless (get-buffer-process "*ruby*")
    (run-ruby "pry" "ruby")
    ))

(with-eval-after-load 'robe
  (unless (get-buffer-process "*ruby*")
    (run-ruby "pry" "ruby"))
  (robe-start))
```

# reproduce:
use upper config, then press `[C-c C-k]` in rails ruby code file to refresh rails code.

# reason
because inf-ruby does not support multiple instances, user can't start inf-ruby-console-auto for general ruby code file, then start a new inf-ruby instance for Rails project.
I want to ask. Is it possible to support in inf-ruby or robe-mode?
- let inf-ruby open process bufffer for separate projects.
- or let robe-use always use single inf-ruby for all.

**Comment by dgutov** [comment]
> I configure inf-ruby and robe-mode like this:

Well, then is was a waste of my time. Just don't do that, the amount of effort you save is negligible.

> let inf-ruby open process bufffer for separate projects

That might be possible, in theory, but the question I'm yet to find an answer for is, how do you track which inf-ruby buffer corresponds to each ruby-mode buffer? We'll need to interact with them from different Ruby buffers, including ones outside of project directories (like in gem sources).

Feel free to open a new issue, here or in inf-ruby.

**Comment by asok** [comment]
> That might be possible, in theory, but the question I'm yet to find an answer for is, how do you track which inf-ruby buffer corresponds to each ruby-mode buffer? 

@dgutov can't we have a plist of project directories and inf-ruby buffer names? The projects directory would have to be taken by calling `projectile-project-root` so this feature would have a dependency on projectile. Although this does not resolve the case of the gem sources.

**Comment by stardiviner** [comment]
This is a solution, and I think is a good idea.

**Comment by dgutov** [comment]
> The projects directory would have to be taken by calling projectile-project-root

No need for projectile, it will probably be the value of `default-directory` in the respective `inf-ruby` buffer. And the `file-in-directory-p` check should suffice. The gem issue is more complicated.

Anyway, as long as we're using inf-ruby, the next step will be to support multiple REPLs there.

**Comment by asok** [comment]
> the next step will be to support multiple REPLs there.
I made a PR that addresses that https://github.com/nonsequitur/inf-ruby/pull/91

**Comment by dgutov** [comment]
I've pushed support for multiple projects to Robe, please take a look.

**Comment by dgutov** [comment]
@asok @stardiviner Anybody using it?

**Comment by stardiviner** [comment]
I will take a try in recent days.

**Comment by stardiviner** [comment]
@dgutov Sorry, I can't test for recent days,My rails new project failed on some problem.
