### ISSUE TITLE
Vim integration

### ISSUE THREAD

**Issue by rorystephenson** [dgutov/robe#38]
Do you intend to integrate with Vim or has anyone managed to get this working with Vim?

**Comment by ypresto** [comment]
I have moved from Vim to Atom. Atom is good editor. :)

I'm working on Atom integration.
https://github.com/ypresto/robe-atom

**Comment by dgutov** [comment]
@ypresto Nice. I won't promise any kind of API stability, but I'll try to notify you of any major changes.

**Comment by ypresto** [comment]
Thank you! I'll track that. :)

2015年6月17日(水) 18:23 Dmitry Gutov <notifications@github.com>:

**Comment by dgutov** [comment]
@ypresto 152ed9efd42d653411f04020bb7b7d80b15f7f2c included a small change in the API, but you don't seem to be using that part yet.

**Comment by ypresto** [comment]
I found that I forgot to implement `initialize` logic... :)

**Comment by dgutov** [comment]
And now you don't need to. But you don't seem to use the navigation capability at all: `methodTargets`, defined in `robe-client.coffee`, is notused anywhere.

**Comment by h-michael** [comment]
+1

**Comment by petRUShka** [comment]
Having vim integration should be very useful!

**Comment by dgutov** [comment]
Now that Solargraph is a thing, and it's working okay with at least some projects, it's probably the better choice for Vim users (less manual intervention needed). So I'm going to close this.
