### ISSUE TITLE
"Private method singleton_method? called for" when jumping to a definition of function inside a module

### ISSUE THREAD

**Issue by sktoiva** [dgutov/robe#44]
When a module function is defined under module_function and called with module as receiver robe-mode's jump-to-definition fails. This outputs "End of file during parsing" to minibuffer and inf-ruby console has an error of 
```
private method `singleton_class?' called for #<Class:0x007fa413878408>
.emacs.d/elpa/robe-20141120.1919/lib/robe/type_space.rb:41:in `reject!'
.emacs.d/elpa/robe-20141120.1919/lib/robe/type_space.rb:41:in `scan_with'
.emacs.d/elpa/robe-20141120.1919/lib/robe/sash.rb:102:in `method_targets'
.emacs.d/elpa/robe-20141120.1919/lib/robe/sash.rb:176:in `public_send'
.emacs.d/elpa/robe-20141120.1919/lib/robe/sash.rb:176:in `call'
.emacs.d/elpa/robe-20141120.1919/lib/robe/server.rb:40:in `block in start'
.emacs.d/elpa/robe-20141120.1919/lib/robe/server.rb:28:in `loop'
.emacs.d/elpa/robe-20141120.1919/lib/robe/server.rb:28:in `start'
```

**Comment by dgutov** [comment]
Thanks for the report.

Could you find out which gem exactly creates a class where `singleton_class?` is made private?
Alternatively, post an example project where that happens.

**Comment by sktoiva** [comment]
I just noticed that this issue concerns also all class methods.

According to your instructions, the problem seems to be with Rails versions 3.2.x and especially the activesupport gem: 

https://github.com/rails/rails/blob/v3.2.19/activesupport/lib/active_support/core_ext/class/attribute.rb#L111

**Comment by dgutov** [comment]
Indeed, Rails is the scumbag. They fixed it in 4.0.4, though.

I'll add a workaround, thanks.

**Comment by dgutov** [comment]
Please test.

**Comment by sktoiva** [comment]
Thank you! It works!
