### ISSUE TITLE
Doc change?: mention inf-ruby instead of inf-ruby-console-auto for non rails applications

### ISSUE THREAD

**Issue by RAbraham** [dgutov/robe#45]
Hi,
I have opened a Sinatra app in Emacs. When I run inf-ruby-console-auto, I get the error:

inf-ruby-console-rails-envs: No files in my_sinatra_app/config/environments/

I tried inf-ruby instead and robe started working. I don't know if this an error on my part (emacs newbie) or something which should be mentioned in the robe docs.

On a separate note, I would like to thank you for the fine work that you have been doing in contributing to the emacs community.

**Comment by dgutov** [comment]
> inf-ruby-console-rails-envs: No files in my_sinatra_app/config/environments/

This sounds like you've recreated a part of Rails application structure inside your Sinatra app, and this makes `inf-ruby-console-auto` confused (that function tries to determine which kind of application it's dealing with). It probably should be considered a bug.

After it's fixed, with Sinatra, you should have better success after adding `racksh` to Gemfile. Then `inf-ruby-console-auto` should load your application, not just a Ruby console.

**Comment by RAbraham** [comment]
To provide you with more information,
 
1) I see the gem 'activesupport' which I guess means the project is reusing Rails utility classes in this Sinatra project(I'm new to ruby/rails/sinatra and it's a client project,not mine). Maybe this may be causing issues too.

2) The project root folder  has /config,/lib,/spec along with Gemfile etc.
