### ISSUE TITLE
'Method not found' for files in Sinatra app when I do robe-jump

### ISSUE THREAD

**Issue by RAbraham** [dgutov/robe#46]
Hi,
I am trying to do robe-jump in a Sinatra app. I open the file application.rb in the Sinatra app. I then do

- M-x rvm-activate-corresponding-ruby ( No visible sign that it works though in the mini-buffer)
- M-x inf-ruby( M-x inf-ruby-console-auto did not work for me. I  guess this may be the offending part. I have documented the issue here at https://github.com/dgutov/robe/issues/45)
- M-x robe-start

* My application.rb calls a file within the same directory (e.g MyClass) as MyClass.new(a,b). When I do robe-jump on the word new, I get 'Method not found' error in the mini-buffer

Things I have tried.
* When I type MyClass in my irb session started by inf-ruby, it raises an uninitialized constant error
* When I do robe-jump on a method which is in the same file as application.rb, it does not recognize it and instead offers to show the method in the third-party gems(i.e. the mini-buffer shows Module: followed by a list of third party modules which have the method). robe-jump and returning back to the original file(application.rb) works when I go to the shown third-party file.  

My system info:
Ruby version: 2.2
Emacs Version:24.4.1
OS: Mac Yosemite

Thanks,
Rajiv

**Comment by dgutov** [comment]
> M-x inf-ruby-console-auto did not work for me. I guess this may be the offending part

It probably is. Your application isn't loaded into the REPL, and so Robe knows nothing about it. Try `C-c C-l` to load specific files, for example.

**Comment by dgutov** [comment]
Maybe try `M-x inf-ruby-console-default` directly.

**Comment by RAbraham** [comment]
Sorry, I forgot to mention, the uninitialized constant error I got in my irb session was after I tried C-c C-l, if that is where I have to test and find out.

**Comment by RAbraham** [comment]
I tried M-x inf-ruby-console-default , going back to the the root folder, it opened up a pry session. I did robe-start after that but same issue.

**Comment by dgutov** [comment]
> the uninitialized constant error I got in my irb session was after I tried C-c C-l

Then you need to load the file that loads the whole application without errors. Or restructure the application so that one exists.

If you're new to Ruby, it might be a bit hard, but that's a good exercise anyway.

**Comment by RAbraham** [comment]
I installed racksh and did M-x inf-ruby-console-default. It opened the Rack Shell. Now,robe-jump works when I do it on MyClass.new(a,b) :+1: 

- However, when I do `M-,( tags-loop-continue)` to return to the calling file, it gives me the following error
`user-error: No ▤ Enter⏎tags-search or ▤ Enter⏎tags-query-replace in progress`

**Comment by dgutov** [comment]
How come `M-,` is bound to `tags-loop-continue` there? In `robe-mode-map`, it's `pop-tag-mark`.

**Comment by RAbraham** [comment]
Exactly :), I had the same suspicion but I could not remember for sure. That's why I mentioned it.

I noticed that when I go into MyClass.new(a,b) method using M-.(robe-jump), it goes into the file MyClass as expected but robe mode is not enabled in the buffer anymore. When I go back using pop-tag-mark to the calling file, robe mode is enabled back again.

**Comment by dgutov** [comment]
Seems like the problem might be with the way you enable `robe-mode`. How do you do that?

**Comment by RAbraham** [comment]
I  closed and restarted emacs. I go to the parent ruby file(robe is enabled by default). I do robe-jump which works and the problem appears as described above

**Comment by dgutov** [comment]
> (robe is enabled by default)

How?

**Comment by RAbraham** [comment]
.. I don't know. My Emacs binding is 
(add-hook 'ruby-mode-hook 'robe-mode)

Some of my emacs package list is : 
  ergoemacs-mode   
  exec-path-from-shell
  inf-ruby           
projectile        
  projectile-rails 
  rake               
  robe

**Comment by dgutov** [comment]
That first line (with `add-hook`) looks right. I don't understand how it could result in `robe-mode` not being enabled in some `ruby-mode` buffers.

**Comment by RAbraham** [comment]
So the add-hook will make robe-mode be enabled by default?

**Comment by RAbraham** [comment]
I'll check why `ruby-mode` is not enabled in other buffers. I have removed a lot of packages. Maybe some of them were interfering

**Comment by dgutov** [comment]
> So the add-hook will make robe-mode be enabled by default?

Yes.

**Comment by RAbraham** [comment]
It works now after I installed rvm. :+1:

**Comment by RAbraham** [comment]
I have to rvm-activate-corresponding-ruby of course, as mentioned in the doc

**Comment by dgutov** [comment]
Err, that looks right, but it shouldn't affect `robe-mode` being enabled or not.

**Comment by RAbraham** [comment]
When I start on a ruby file, robe mode is on. If I don't do `rvm-activate-corresponding-ruby` before I do `robe-jump`,then when it gives me 'No ruby console running. Launch automatically(yes or no?)' and I answer yes, it gives me the error `apply: Searching for program: no such file or directory, bundle.`

Does that seem like expected behaviour?

**Comment by dgutov** [comment]
Pretty much. RVM requires hand-holding.
