### ISSUE TITLE
Documentation: Should racksh gem also be included in bundler for Rails Apps

### ISSUE THREAD

**Issue by RAbraham** [dgutov/robe#48]
Hi,
Robe jump worked for me only after adding racksh ( in addition to pry,pry-doc etc.) in the Gemfile for a Rails app.
Is this a general thing which should be mentioned in the documentation or I could be  special case..

**Comment by dgutov** [comment]
Check out https://github.com/nonsequitur/inf-ruby#usage. I don't know, maybe we should refer to that section more prominently.
