### ISSUE TITLE
Running robe-start produces error

### ISSUE THREAD

**Issue by sktoiva** [dgutov/robe#51]
When running ```robe-start```, I get first ```Wrong type argument: stringp, nil``` from ```(get-buffer inf-ruby-buffer)```. This is apparently because ```inf-ruby-buffer``` returns nil. If I run ```inf-ruby-console-auto``` manually before ```robe-start``` I get forwards but receive the following stacktrace:

```
[1] pry(main)> => "robe on"
[2] pry(main)> E, [2015-02-18T11:19:06.784630 #14917] ERROR -- : Request failed: /rails_refresh/. Please file an issue.
E, [2015-02-18T11:19:06.784707 #14917] ERROR -- : uninitialized constant Robe::Sash::ActionDispatch
/.emacs.d/elpa/robe-20150216.1624/lib/robe/sash.rb:165:in `rails_refresh'
/.emacs.d/elpa/robe-20150216.1624/lib/robe/sash.rb:176:in `public_send'
/.emacs.d/elpa/robe-20150216.1624/lib/robe/sash.rb:176:in `call'
/.emacs.d/elpa/robe-20150216.1624/lib/robe/server.rb:40:in `block in start'
/.emacs.d/elpa/robe-20150216.1624/lib/robe/server.rb:28:in `loop'
/.emacs.d/elpa/robe-20150216.1624/lib/robe/server.rb:28:in `start'
/.emacs.d/elpa/robe-20150216.1624/lib/robe.rb:18:in `block in start'
```

**Comment by dgutov** [comment]
The backtrace looks like you're called `robe-rails-refresh`, in a non-Rails project.

**Comment by dgutov** [comment]
Does `robe-start` show you the same error when you call it in a new Emacs session (with a Ruby file opened, or course)?

**Comment by sktoiva** [comment]
Actually, sorry - I gave a bit false information by mistake.

These issues arise when running ```robe-rails-refresh``` in a Rails project with ```C-c C-k```. First I get the ```Wrong type argument: stringp, nil``` which comes from robe-start. And then if I manually start the console, I get forwards and that error is produced. 

So, ```robe-start``` starts working after ```inf-ruby-console-auto``` but then ```robe-rails-refresh``` fails. I'm in a Rails project. I even tested the ```robe-start``` with a new Emacs session as suggested.

This failure started happening after I updated robe to the version 20150216.1624.

**Comment by kofno** [comment]
Seeing the same problem on the same version. Haven't investigated it yet.

**Comment by dgutov** [comment]
Right. Sorry about that, should be fine now.

**Comment by kofno** [comment]
Thank you!

**Comment by sktoiva** [comment]
That fixed the first issue about ```inf-ruby-buffer```, thank you!

 However, the second one remains about the ```robe-rails-refresh```.

**Comment by dgutov** [comment]
@sktoiva Ok, what version of Rails are you using? Does you application have a `bin/rails` file in it?

If not, either `touch bin/rails` or try `M-x inf-ruby-console-rails` to launch the Rails console explicitly.

**Comment by sktoiva** [comment]
My project is still running on Rails 3.2.21 and it doesn't have ```bin/rails``` file. Touching it made the problem go away.

**Comment by dgutov** [comment]
@sktoiva Do you know why? My Rails 3.2 sample app has this file.

Anyway, this is an outcome of https://github.com/nonsequitur/inf-ruby/issues/67. Better suggestions welcome.

**Comment by sktoiva** [comment]
Thanks, moved the discussion there.
