### ISSUE TITLE
[Feature Request] replace globally in current things

### ISSUE THREAD

**Issue by zw963** [dgutov/robe#57]
e.g.

```ruby
def as_indexed_json(options = {})
    _attributes = attributes.as_json
    _attributes["status"] ||= 0  <== cursor is here
    _attributes.as_json(:except => "additional_fields")
  end
```

run `(anzu-replace-at-cursor-thing)`, it just replace last _attributes, 
replace worked like this, but, I thought if I definition myself thing,
I hope can replace 3 occur _attributes in current method.

Thanks.

**Comment by zw963** [comment]
Sorry, could you delete this post ? wrong place.

**Comment by dgutov** [comment]
Keeping it closed is the best we can do.
