### ISSUE TITLE
Problems with autocomplete from words in current buffer

### ISSUE THREAD

**Issue by anquegi** [dgutov/robe#59]
Hi I have this configuration for ruby development

;; Files with the following extensions should open in ruby-mode
(add-to-list 'auto-mode-alist '("\.rb$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\.gemspec$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\.ru$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile$" . ruby-mode))

(require 'ruby-mode)
(require 'inf-ruby)

;; When folding, take these delimiters into consideration
(add-to-list 'hs-special-modes-alist
'(ruby-mode
"\(class\|def\|do\|if\)" "\(end\)" "#"
(lambda (arg) (ruby-end-of-block)) nil))

;; RVM support
(require 'rvm)
(rvm-use-default)

;; Cucumber
(require 'feature-mode)
(setq feature-use-rvm t) ;; Tell cucumber to use RVM
(setq feature-cucumber-command "cucumber {options} {feature}")
;; .feature files should open in feature-mode
(add-to-list 'auto-mode-alist '(".feature$" . feature-mode))

;; Rspec
(require 'rspec-mode)
;; I want rspec instead of rake spec
(setq rspec-use-rake-when-possible nil)
;; Scroll to the first test failure
(setq compilation-scroll-output 'first-error)

;; Projectile mode
(require 'projectile)
(projectile-global-mode)
(setq projectile-completion-system 'grizzl)

;; Prevent emacs from adding the encoding line at the top of the file
(setq ruby-insert-encoding-magic-comment nil)

;; Functions to help with refactoring
(require 'ruby-refactor)
(add-hook 'ruby-mode-hook 'ruby-refactor-mode-launch)
;; Easily toggle ruby's hash syntax
(require 'ruby-hash-syntax)
;; Ruby rdoc helpers mostly
(require 'ruby-additional)
;; Helpers to deal with strings and symbols
(require 'ruby-tools)
;; Support for YARD
(require 'yard-mode)
(add-hook 'ruby-mode-hook 'yard-mode)
;; Support for running rspec tests
(require 'rspec-mode)

;; Turn on eldoc in ruby files to display info about the
;; method or variable at point
(add-hook 'ruby-mode-hook 'eldoc-mode)
;; Switch the compilation buffer mode with C-x C-q (useful
;; when interacting with a debugger)
(add-hook 'after-init-hook 'inf-ruby-switch-setup)

(add-hook 'ruby-mode-hook
(lambda ()
(hs-minor-mode 1) ;; Enables folding
(modify-syntax-entry ?: "."))) ;; Adds ":" to the word definition

;; Start projectile-rails
(add-hook 'projectile-mode-hook 'projectile-rails-on)

;; robe autocompletion
(add-hook 'ruby-mode-hook 'robe-mode)
(global-company-mode t)
;;(push 'company-robe company-backends)
(eval-after-load 'company
'(progn
(push 'company-robe company-backends)
(push 'company-inf-ruby company-backends)))

;;(add-hook 'robe-mode-hook 'ac-robe-setup)
;;(add-hook 'robe-mode-hook
;; (lambda ()
;; (add-to-list 'ac-sources 'ac-source-robe)
;; (setq completion-at-point-functions '(auto-complete))))

(defadvice inf-ruby-console-auto (before activate-rvm-for-robe activate)
(rvm-activate-corresponding-ruby))

things works well but for example, company completes well the method say_hello...

captura de pantalla de 2015-07-15 13 23 28

then I can see the methods in inf-ruby

captura de pantalla de 2015-07-15 13 23 52

but when I make robe-start I can see ruby methods but not say_hello..

captura de pantalla de 2015-07-15 13 24 04

so here the problem after robe-start

captura de pantalla de 2015-07-15 13 24 23

If some body can help me, it will be good, thanks

![captura0](https://cloud.githubusercontent.com/assets/2518346/8899672/cb8f1a6a-3437-11e5-990e-5043e59f6d7e.png)
![captura1](https://cloud.githubusercontent.com/assets/2518346/8899673/cb94c5a0-3437-11e5-80b9-a282b2a628bd.png)
![captura2](https://cloud.githubusercontent.com/assets/2518346/8899674/ccf9ca76-3437-11e5-8c05-068c13563a18.png)
![captura3](https://cloud.githubusercontent.com/assets/2518346/8899675/cd17eee8-3437-11e5-9753-f9ecb4647846.png)

**Comment by dgutov** [comment]
Please read the README. In particular, the last paragraph in the introduction. "As you change the code..."
