### ISSUE TITLE
Completion doesn't work for ::-prefixed constants

### ISSUE THREAD

**Issue by jetaggart** [dgutov/robe#67]
If I type something like:

`Fo` it will complete `Foo`, however if I type `::Fo` it will not find `Foo`. I think this is the right place to submit this issue. I'd be happy to attempt a fix if you can point me in the right direction.

**Comment by dgutov** [comment]
Thanks for the report, this is the right place. I've noticed the issue, just never got around to fixing it.

**Comment by jetaggart** [comment]
:+1:
