### ISSUE TITLE
emacs freeze sometimes in robe-doc and call robe-jump-modules recursively

### ISSUE THREAD

**Issue by zhengjiezxxy** [dgutov/robe#68]
This is backtrace. It will call robe-jump-modules forever until you press c+g

  (let (super) (edebug-after (edebug-before 3) 15 (if (edebug-after (edebug-before 4) 9 (save-excursion (edebug-after (edebug-before 5) 6 (end-of-thing (quote symbol))) (edebug-after (edebug-before 7) 8 (looking-at "!")))) (progn (edebug-after (edebug-before 10) 14 (setq thing (edebug-after (edebug-before 11) 13 (concat ... "!"))))))) (edebug-after (edebug-before 16) 28 (if (edebug-after 0 17 target) nil (edebug-after (edebug-before 18) 27 (if (edebug-after (edebug-before 19) 21 (string= (edebug-after 0 20 thing) "super")) (progn (edebug-after (edebug-before 22) 26 (setq thing ... super t))))))) (edebug-after (edebug-before 29) 38 (if (edebug-after (edebug-before 30) 35 (and (edebug-after 0 31 target) (edebug-after (edebug-before 32) 34 (string= (edebug-after 0 33 thing) "new")))) (progn (edebug-after (edebug-before 36) 37 (setq thing "initialize" instance t))))) (edebug-after (edebug-before 39) 54 (if (edebug-after (edebug-before 40) 48 (and (edebug-after 0 41 target) (edebug-after (edebug-before 42) 47 (save-excursion (edebug-after ... 44 ...) (edebug-after ... 46 ...))))) (progn (edebug-after (edebug-before 49) 53 (setq thing (edebug-after (edebug-before 50) 52 (concat ... "="))))))) (edebug-after (edebug-before 55) 62 (robe-request "method_targets" (edebug-after 0 56 thing) (edebug-after 0 57 target) (edebug-after 0 58 module) (edebug-after 0 59 instance) (edebug-after 0 60 super) (edebug-after 0 61 robe-jump-conservative))))
  (lambda (thing) (edebug-enter (quote robe-jump-modules) (list thing) (function (lambda nil (let* ((--cl-rest-- (edebug-enter ... nil ...)) (target (if ... ... ...)) (module (car-safe ...)) (instance (car-safe ...)) (ctx (car --cl-rest--))) (edebug-enter (quote edebug-anon100710) (list target module instance ctx) (function (lambda nil ...))))))))(#("set!" 0 3 (fontified t) 3 4 (fontified t syntax-table (3))))
  apply((lambda (thing) (edebug-enter (quote robe-jump-modules) (list thing) (function (lambda nil (let* ((--cl-rest-- (edebug-enter ... nil ...)) (target (if ... ... ...)) (module (car-safe ...)) (instance (car-safe ...)) (ctx (car --cl-rest--))) (edebug-enter (quote edebug-anon100710) (list target module instance ctx) (function (lambda nil ...)))))))) #("set!" 0 3 (fontified t) 3 4 (fontified t syntax-table (3))))
  #[385 "	\203\f\300	=\203\f\304\300N\305\204\306\307\300\"\210\n\204&\310\"\262\202V\305\211\211\311\311HTI\266\312 \262\310\"\262\312 \262\211\313\313H\314\315\"!\266\202\\I\266	\203b\300	=\203b\305\207" [robe-jump-modules elp-master elp-record-p elp-timer-info-property t nil error "%s is not instrumented for profiling" apply 0 current-time 1 float-time time-subtract] 16 "This function has been instrumented for profiling by the ELP.\nELP is the Emacs Lisp Profiler.  To restore the function to its\noriginal definition, use \\[elp-restore-function] or \\[elp-restore-all].\n\n(fn FUNC &rest ARGS)"]((lambda (thing) (edebug-enter (quote robe-jump-modules) (list thing) (function (lambda nil (let* ((--cl-rest-- (edebug-enter ... nil ...)) (target (if ... ... ...)) (module (car-safe ...)) (instance (car-safe ...)) (ctx (car --cl-rest--))) (edebug-enter (quote edebug-anon100710) (list target module instance ctx) (function (lambda nil ...)))))))) #("set!" 0 3 (fontified t) 3 4 (fontified t syntax-table (3))))
  apply(#[385 "	\203\f\300	=\203\f\304\300N\305\204\306\307\300\"\210\n\204&\310\"\262\202V\305\211\211\311\311HTI\266\312 \262\310\"\262\312 \262\211\313\313H\314\315\"!\266\202\\I\266	\203b\300	=\203b\305\207" [robe-jump-modules elp-master elp-record-p elp-timer-info-property t nil error "%s is not instrumented for profiling" apply 0 current-time 1 float-time time-subtract] 16 "This function has been instrumented for profiling by the ELP.\nELP is the Emacs Lisp Profiler.  To restore the function to its\noriginal definition, use \\[elp-restore-function] or \\[elp-restore-all].\n\n(fn FUNC &rest ARGS)"] (lambda (thing) (edebug-enter (quote robe-jump-modules) (list thing) (function (lambda nil (let* ((--cl-rest-- (edebug-enter ... nil ...)) (target (if ... ... ...)) (module (car-safe ...)) (instance (car-safe ...)) (ctx (car --cl-rest--))) (edebug-enter (quote edebug-anon100710) (list target module instance ctx) (function (lambda nil ...)))))))) #("set!" 0 3 (fontified t) 3 4 (fontified t syntax-table (3))))
  robe-jump-modules(#("set!" 0 3 (fontified t) 3 4 (fontified t syntax-table (3))))
  robe-eldoc()
  eldoc-print-current-symbol-info()
  #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([nil 0 0 500000 t #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])

**Comment by dgutov** [comment]
There's only one call to `robe-jump-modules` in this backtrace. Why are you saying it's being called recursively?

How do I reproduce this?

**Comment by zhengjiezxxy** [comment]
I guess maybe there is some  timeout of eldoc function in this timer "timer-event-handler([nil 0 0 500000 t #[0 "�\204� \205�\n\303>?\205�\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])", and my machine is a old machine, so it begins another round of eldoc after completing last eldoc. And in my machine, acompany-complete are also very 
slowly, about 15s.

**Comment by dgutov** [comment]
Have you tried completion in a small sample project? Is the problem the same there?

**Comment by zhengjiezxxy** [comment]
I tried a small rails test project, the problem is the same.

**Comment by dgutov** [comment]
What's your Emacs version?

**Comment by zhengjiezxxy** [comment]
I use emacs 25.3. And I found that most time are consumed in robe-doc-for and url-retrieve-synchronously but some url-* function is very fast. So I guess some function in robe server may be slow in some case. Still debugging.

**Comment by dgutov** [comment]
> I use emacs 25.3

You probably mean 24.3.

> So I guess some function in robe server may be slow in some case.

There many be a few `/tmp/robe-access-XXXXX.log` files, named after the currently used port. Open the most recently changed one and take a look which requests take the most time. But first of all, check whether it's the Ruby backend that takes a lot of time.

**Comment by zhengjiezxxy** [comment]
I use 25.0 not 25.3. And I found emacs freeze at accept-process-out in url-retrieve-synchronously when there is two requests to the robe server and freeze at second request. The first one is like: /method_targets/xxxxx/yes/xxxx, the second is like: /doc_for/xxxx/yes/xxxx

**Comment by dgutov** [comment]
@zhengjiezxxy When have you last updated it? If it's old, your problem can be the same as #36.

**Comment by zhengjiezxxy** [comment]
#36 works for me. Thanks!

**Comment by dgutov** [comment]
What does?

#36 is *fixed*, in the Emacs master.

**Comment by zhengjiezxxy** [comment]
I pull the change and rebuild emacs and then no freeze any more.

**Comment by dgutov** [comment]
:thumbsup:
