### ISSUE TITLE
invalid multibyte char error on UTF8 characters

### ISSUE THREAD

**Issue by lethjakman** [dgutov/robe#70]
If any of my gemspecs contain utf8 characters robe throws an exception about invalid multibyte characters. 

/Users/me/Documents/workspace/apps_env/<my_project>/<my_project.gemspec:11: invalid multibyte char (US-ASCII)
/Users/me/Documents/workspace/apps_env/<my_project>/<my_project>.gemspec:11: syntax error, unexpected end-of-input, expecting keyword_end
  s.summary     = "Répondez S'il VIEW Plaît"

**Comment by dgutov** [comment]
Robe doesn't load your `.gemspec` files. It calls `inf-ruby-console-auto`, and that command, when called inside a gem, calls something like `(run-ruby "bundle exec irb")`.

The error above signals that Ruby 1.9 is being used with a file that uses UTF-8, but doesn't have the "magic comment". You should probably check that your Emacs is properly integrated with your RVM, rbenv or chruby installation.
