### ISSUE TITLE
Support completion of variable names

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#75]
I found robe does not support complete class instance object:
here is the demo code:

``` ruby
module Test
  class Person
    @@name = 'chris'
    def hello(name)
      p 'hi', name
    end
  end
end

person1 = Test::Person.new

person1.hello('chris')
```

Load source code with `[C-c C-l]`, then input `pers`, but no complete.
When I input `pers`, but robe does not give out complete candidates.

Then I checked out the README doc, saw only methods and constants completion supported.

Is it easy to add this support?

BTW: might be related.
Definition jump only support methods jumping, not support variable, class instance etc. Like upper code `person1`.

**Comment by dgutov** [comment]
> class instance object

I think they are just called local variables.

> Is it easy to add this support?

Yes and no. I haven't decided yet how we'll do that here.

**Comment by stardiviner** [comment]
I see.

**Comment by dgutov** [comment]
I've added an implementation in Emacs Lisp. It's imperfect, but much better than nothing.

No "jump to declaration", though.
