### ISSUE TITLE
Error when using with chruby

### ISSUE THREAD

**Issue by Immortalin** [dgutov/robe#76]
I am using robe with the default ruby configuration layer from spacemacs with chruby to switch between rubies. 
When connecting to the repl, I am getting this error:
```sh
apply: Searching for program: no such file or directory, bundle
```

**Comment by dgutov** [comment]
Apparently that means you need some additional configuration to use Emacs with `chruby` rubies. See https://github.com/plexus/chruby.el, for example.

For my part, I recommend using `rbenv`: properly configured, it just work everywhere, both in the shell and inside Emacs.

**Comment by Immortalin** [comment]
[This](https://github.com/mveytsman/.emacs.d/blob/master/user-lisp/setup-ruby-mode.el) seem to work. I haven't tested it out yet. Maybe add it to README.md?

**Comment by dgutov** [comment]
I can add it, but please test it out first.

**Comment by dgutov** [comment]
@Immortalin Well?

**Comment by dgutov** [comment]
Patch welcome.

**Comment by Immortalin** [comment]
@dgutov sorry, haven't had time to work on it
