### ISSUE TITLE
Robe running fault

### ISSUE THREAD

**Issue by we138** [dgutov/robe#77]
Hello, I try to start robe plugin but I get buffer with message about error "process rails segmentation fault (core dumped)".My configuration: ubuntu 12.04, emacs 24, ruby 2.2.1, rails 4.2.4

**Comment by dgutov** [comment]
Hi!

Sorry, there's not much I can do: a segfault most likely means a bug in Ruby. Try different versions of Rails, a newer Ruby (how about 2.2.2?). Maybe a newer Ubuntu?

**Comment by dgutov** [comment]
Also see https://github.com/nonsequitur/inf-ruby/issues/78#event-451082283. The reporter there has the same Ubuntu version.
