### ISSUE TITLE
robe launch error with Ruby 2.3.0-dev

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#78]
I got this error when I start robe with `robe-start`.

```
irb(main):012:0> LoadError: cannot load such file -- pry
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/sash/doc_for.rb:1:in `<top (required)>'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/sash.rb:1:in `<top (required)>'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe.rb:1:in `<top (required)>'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):12
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/bin/irb:11:in `<main>'
```

I don't understand why robe-start will try to load "pry".

**Comment by dgutov** [comment]
What's not to understand? It's in the requirements.

**Comment by stardiviner** [comment]
I have not relized that pry is required by robe. (I searched robe source code, I did found it now)
Why here pry is unavailable?

**Comment by dgutov** [comment]
Do you have Gemfile in that project? Is pry in Gemfile?

**Comment by stardiviner** [comment]
I have an empty `Gemfile` with out any content.
I tried to delete directory `Gems/` and `Gemfile.lock`.
Does not work.

**Comment by dgutov** [comment]
Remove Gemfile, then?

Try to read about how bundler works. Either don't have a Gemfile, or you must put all dependencies into it.

**Comment by dgutov** [comment]
And make sure you have `pry` installed in that `2.3.0-dev` version of Ruby.

**Comment by stardiviner** [comment]
I have not delete that `Gemfile`. I tried `bundle install`. no gems dependency.
and I check out `pry` path, it is in Ruby version `2.3.0-dev`. I manage Ruby version with `rbenv`.

**Comment by dgutov** [comment]
I don't understand what you're saying, sorry.

**Comment by stardiviner** [comment]
I mean, I start robe, but pry (which is required by robe) is not available. This caused upper error output in my question.
I tried some methods (in upper posts) but still does not work.
This is what I'm saying.

**Comment by dgutov** [comment]
Make it available, then. It's not rocket science. As a Ruby programmer, you should know how to do that.

**Comment by stardiviner** [comment]
I found out why now with command `gem environment`
I have a gemset for rbenv named `global`.
Problem solved.

**Comment by dgutov** [comment]
Glad you solved it. But gemsets with `rbenv`? Why? No wonder you're having problems.
