### ISSUE TITLE
'Method not found' and 'Cannot locate this method' ...

### ISSUE THREAD

**Issue by rdallasgray** [dgutov/robe#8]
I'm having some trouble getting robe to work properly ... I've got the necessary gems installed, and I'm starting robe in a gem with standard layout. The inf-ruby process appears to start (with buffer name `*gem*`), but hitting M-. just prints the message 'Method not found', whatever method point is at.

Similarly, only some documentation appears: mostly, I just get the message 'Cannot locate this method: [method]. Try 'gem install pry-doc ...`' etc. (I do have pry-doc installed). 

Do you have any tips, or a step-by-step to get things working correctly?

**An update and clarification on this:** the second problem is solved by including pry and pry-doc as development dependencies in the gemspec (the project in question is a gem). Still no method-at-point navigation though.

**Comment by ruskotron** [comment]
I would just like to point out for others having this problem, that the  jump-to-method function worked as expected when I manually "required" the file in the irb.

In irb I first did a `puts $:` to confirm my load-path and then did `require "dir1/dir2/my_ruby_file"` which returned true and then after this it worked.

**Comment by dgutov** [comment]
Manually requiring the file is indeed one of the ways to handle this.

**Comment by ruskotron** [comment]
Is there a way that it can do this automatically? It should be straightforward enough considering it's the file that I'm editing?

**Comment by dgutov** [comment]
When it's the file you're currently editing, pressing `C-c C-l` should be easy enough.

**Comment by ruskotron** [comment]
There is a prompt in the notification area, which confusingly says my working file is the default but also includes the working directory pre-filled.

Anyway, I just pressed enter without making any modifications and the Jump to method feature works beautifully! Jumps within file and also to methods defined elsewhere and in gems without any fuss.

Thank you!
