### ISSUE TITLE
robe load rails error

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#80]
This is the error output in buffer `*ruby*`.
```
irb(main):002:0> E, [2016-01-19T23:19:11.172413 #10850] ERROR -- : Request failed: /rails_refresh/. Please file an issue.
E, [2016-01-19T23:19:11.172553 #10850] ERROR -- : uninitialized constant Robe::Sash::ActionDispatch
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/sash.rb:176:in `rails_refresh'
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/sash.rb:188:in `public_send'
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/sash.rb:188:in `call'
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/server.rb:39:in `block in start'
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/server.rb:27:in `loop'
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe/server.rb:27:in `start'
/home/stardiviner/.emacs.d/elpa/robe-20151230.449/lib/robe.rb:20:in `block in start'
```

My environment info:
```
Rails 4.2.5
ruby 2.3.0p2 (2015-12-25 revision 53297) [x86_64-linux]
rbenv 1.0.0-14-gc388331
```

I tried to debug it in `pry` by `require './robe.rb'` in `robe/lib`.
But I got error info:
```
LoadError: cannot load such file -- robe/sash
from /home/stardiviner/Code/Emacs/robe/lib/robe.rb:1:in `require'
```

**Comment by dgutov** [comment]
`ActionDispatch` not being loaded means Rails is *not* in your environment.

How do you launch Robe?

**Comment by dgutov** [comment]
https://github.com/dgutov/robe/issues?q=is%3Aissue+ActionDispatch+is%3Aclosed

**Comment by stardiviner** [comment]
I'm using `rbenv.el`, and launch robe with `M-x inf-ruby`, then `M-x robe-start`.
And it shows `"robe on 40344"`
Then I open the `Gemfile` under Rails project root, enable `robe-mode`, and press `[C-c C-k]` to load Rails.
And open file `app/controller/application_controller.rb` under Rails project root. then repeat upper steps. got same error.

I tried command `inf-ruby-console-rails`. specify the Rails root directory, and choose `development` environment. It can work.

**Comment by dgutov** [comment]
> launch robe with M-x inf-ruby

And that is your problem. Like I've explained in the README, and in the issues, including to you personally, Robe needs the application environment loaded. `M-x inf-ruby` just calls `irb`.

> I tried command inf-ruby-console-rails. specify the Rails root directory, and choose development environment. It can work.

So it works? Case closed? Or do you have any further questions?

**Comment by stardiviner** [comment]
Sorry, I misunderstand your answer. It's ok now.

**Comment by dgutov** [comment]
Good.
