### ISSUE TITLE
Add debug manual to README

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#81]
I found robe is very slow (about 4 seconds) when completing. I hope you can add a manual in README about how to debug robe **deeply**.

**Comment by dgutov** [comment]
> debug manual

You read the README, read the code, understand it all thoroughly, and debug it. ;-)

Completion taking 4 seconds is possible if the prefix is empty, and Robe doesn't know the type of the target (so it returns all methods from all classes). That's why #26 is still open.

**Comment by dgutov** [comment]
@stardiviner Check out the latest commit. It should improve on those 4 seconds.

**Comment by stardiviner** [comment]
I tried out the latest commit, it does speed up. Thanks very much.
