### ISSUE TITLE
In Spacemacs installation fails via package-install

### ISSUE THREAD

**Issue by antonpaisov** [dgutov/robe#83]
Hello,
I've tried to install robe via package install and it fails with this message
https://www.dropbox.com/s/stao8sc8362qnn9/Screenshot%202016-03-18%2001.00.51.png?dl=0
I can still see the package on melpa though http://melpa.org/#/robe
Can you help, please?)

**Comment by dgutov** [comment]
Looks like it could be a problem in MELPA. But maybe everything's fine: do you perform the install from `M-x list-packages`?

**Comment by antonpaisov** [comment]
I've used `M-x package-install`, install works after I've used `M-x list-packages`
However still can't manage to get things working :) but will figure it out now
Thank you!
