### ISSUE TITLE
How to debug robe or maybe inf-ruby when I got nothing output in robe log file?

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#85]
I found robe completion will lost response when I quickly delete some characters, and query doc with `robe-doc` or something else after a few hours.

I have to kill the inferior buffer `*rails*`, then restart it again. then it can work.

I try to find out why:
- test with `$ emacs -q`. sometimes happened, not always.
- I tried to track down the robe log file `/tmp/robe-access-[PORT].log`. no output when Emacs lost respond from robe completing.

Can you help me on this? Thanks.

**Comment by dgutov** [comment]
Generally, you look at the last `robe-access-xxxx.log` entry that didn't get a response. I.e. the query that executes too long. Then try to repeat it and see if the response again comes too slowly.
