### ISSUE TITLE
Could not find this project using GitHub search

### ISSUE THREAD

**Issue by zw963** [dgutov/robe#86]
Github Search `robe`,  we get  1,658 repository results,

But i could not found out current.

Does this is a issue ?

**Comment by dgutov** [comment]
I find it right away. But try searching for `ruby robe`, maybe?

**Comment by zw963** [comment]
![recorded1312222075.gif](http://zw963.github.io/recorded1312222075.gif)

**Comment by dgutov** [comment]
Oh, okay. That is weird.

Any suggestions on how to improve the searchability? Aside from a full rename.

**Comment by zw963** [comment]
No idea. Sorry.

May be create a issue to github?

**Comment by zw963** [comment]
It so wierd though, my memory is bad, so i find out  package from github search,
it almost awlays could get what i want by this way, But, i have to open local `robe.el`
to find out this project url.

**Comment by zw963** [comment]
Though could found this project from my `stared` lists.

**Comment by ypresto** [comment]
Perhaps because this repo is fork of another repo.
Contact github to make it root repo..!

**Comment by dgutov** [comment]
That's a good point. And I can just create a new repo, and push the code there.

Will do that sometime later (probably after a rewrite and rename).

**Comment by dgutov** [comment]
This is done now.

Not a year too soon. :roll_eyes:
