### ISSUE TITLE
Support for RubyMotion projects

### ISSUE THREAD

**Issue by jojojames** [dgutov/robe#87]
Trying to jump to test_test will result in 'method not found'. Calling robe-start returns no errors. This seems to be working in my rails project.

```ruby
class Network

  def init
    host = "http://localhost:3000"
    @client = AFMotion::SessionClient.build(host) do
      header "Accept", "application/json"
      response_serializer :json
    end
    self
  end

  def blah_blah
    test_test
  end

  def test_test
  end

end
```

RubyMotion project structure

   |-app
   |---mopub
   |---network
   |-build
   |---iPhoneSimulator-9.3-Development
   |-----client.app
   |-------MRAID.bundle
   |-------client.app.dSYM
   |---------Contents
   |-----------Resources
   |-------------DWARF
   |-------launch_screen.storyboardc
   |-----client.app.dSYM
   |-------Contents
   |---------Resources
   |-----------DWARF
   |-----objs
   |-------Users
   |---------me_user
   |-----------Developer
   |-------------testapp
   |---------------client
   |-----------------app
   |-------------------mopub
   |-------------------network
   |-resources
   |-spec
   |-vendor
   |---Pods
   |-----AFNetworking
   |-------AFNetworking
   |-------UIKit+AFNetworking
   |-----Headers
   |-------Private
   |---------AFNetworking
   |---------mopub-ios-sdk
   |-------Public
   |---------AFNetworking
   |---------mopub-ios-sdk
   |-----Local Podspecs
   |-----Pods.xcodeproj
   |-------xcuserdata
   |---------me_user.xcuserdatad
   |-----------xcschemes
   |-----Resources
   |-------MRAID.bundle
   |-----Target Support Files
   |-------AFNetworking
   |-------Pods-RubyMotion
   |-------mopub-ios-sdk
   |-----build-iPhoneSimulator
   |-----mopub-ios-sdk
   |-------MoPubSDK
   |---------Internal
   |-----------Banners
   |-----------Common
   |-------------AdAlerts
   |-----------Event Logging
   |-----------Fabric
   |-----------HTML
   |-----------Interstitials
   |-----------MRAID
   |-----------Utility
   |-------------Categories
   |-----------VAST
   |---------Native Ads
   |-----------Internal
   |-------------Categories
   |---------NativeVideo
   |-----------Internal
   |---------Resources
   |-----------MRAID.bundle
   |---------RewardedVideo
   |-----------Internal
   |---build
   |-----Pods.build
   |-------Release-iphoneos
   |---------AFNetworking.build
   |---------Pods-RubyMotion.build
   |-------Release-iphonesimulator
   |---------AFNetworking.build
   |-----------Objects-normal
   |-------------i386
   |-------------x86_64
   |---------Pods-RubyMotion.build
   |-----------Objects-normal
   |-------------i386
   |-------------x86_64
   |---------Pods.build
   |-----------Objects-normal
   |-------------i386
   |-------------x86_64
   |---------mopub-ios-sdk.build
   |-----------Objects-normal
   |-------------i386
   |-------------x86_64

**Comment by dgutov** [comment]
Using RubyMotion, can you launch a REPL that has your project loaded? How do you do that?

**Comment by jojojames** [comment]
Running rake builds and runs the app as well as launches a REPL that has some connectivity with the running app itself.

Re: project load in the REPL, I might have to do some more research there and get back to you.

**Comment by dgutov** [comment]
> Re: project load in the REPL, I might have to do some more research there and get back to you.

Thanks. That's the main issue; if you can't load your project into a normal Ruby REPL, we can't perform the runtime introspection on which most of Robe's features are built.

**Comment by jojojames** [comment]
Looks like pry isn't supported with RubyMotion.

**Comment by dgutov** [comment]
That's too bad. I wasn't asking about Pry, though. While it would be great if it was supported, we don't do everything through it, and we could try implementing other operations differently if RubyMotion had sufficient runtime introspection capabilities.

**Comment by jojojames** [comment]
What kind of functionality should be I be looking for with the RubyMotion REPL if I keep digging around? I'll probably peek at the robe source but a step in the right direction would be great.

**Comment by dgutov** [comment]
Like `ObjectSpace.each_object`, `Module#name`, `Method#source_location`, `Module#public_instance_methods`, `Module#ancestors` and `Module#included_modules`. This is probably not exhaustive.

**Comment by jojojames** [comment]
Thanks, that should get me started.

**Comment by jojojames** [comment]
From that list, looks like ObjectSpace is not available but the other methods are. All those extra methods in the instance_methods call must be linked to the NSObject class in objective-c.

    module JojoModule
    include Math
    CONST = 1
    def meth
        a = 3
    end

    def woof
        b = 3
    end
    end


     Build ./build/iPhoneSimulator-9.3-Development
    Create ./build/iPhoneSimulator-9.3-Development/client.app/Info.plist
  Simulate ./build/iPhoneSimulator-9.3-Development/client.app
*** Starting simulator
(main)> JojoModule.name 
JojoModule.name 
=> "JojoModule"
(main)> JojoModule#woof.source_location
JojoModule#woof.source_location
=> JojoModule
(main)> JojoModule#public_instance_methods
JojoModule#public_instance_methods
=> JojoModule
(main)> JojoModule#instance_methods
JojoModule#instance_methods
=> JojoModule
(main)> JojoModule.public_instance_methods
JojoModule.public_instance_methods
=> [:woof, :meth, :"conformsToProtocol:", :"mf_objectWithHighest:", :"mf_performOnewaySelectorInMainThread:withObject:withObject:", :"da_addNullRunLoopSourceAndPerformSelector:withObject:afterDelay:inModes:", :"da_performSelectorThatDoesntAffectRetainCount:withObject:", :pl_briefDescription, :MPMediaLibraryDataProviderSystemML3CoercedString, :MP_shortDescription, :"registerForTimeMarkerNotificationsIfNecessaryForPlayer:", :unregisterForTimeMarkerNotifications, :"cancelPreviousDispatchAsyncWithCancellationIdentifier:", :"dispatchAsyncWithCancellationIdentifier:delay:queue:block:", :"ICLogging_isLoggingEnabledAtLevel:", :"cn_updateDictionaryForKey:withChanges:", :ml_stringValueForSQL, :"ml_bindToSQLiteStatement:atPosition:", :"ml_matchesValue:usingComparison:", :"shouldUpdateFocusFromView:toView:heading:", :"willUpdateFocusInContext:withAnimationCoordinator:", :"willUpdateFocusToView:", :"didUpdateFocusFromView:", :className, :accessibilityIdentifier, :"setAccessibilityIdentifier:", :defaultAccessibilityTraits, :isAccessibilityElementByDefault, :isElementAccessibilityExposedToInterfaceBuilder, :"accessibilitySetIdentification:", :accessibilityElements, :"setAccessibilityElements:", :accessibilityElementCount, :"accessibilityElementAtIndex:", :"indexOfAccessibilityElement:", :accessibilityIncrement, :accessibilityDecrement, :"accessibilityScroll:", :accessibilityPerformEscape, :accessibilityPerformMagicTap, :accessibilityActivate, :"setAccessibilityCustomActions:", :accessibilityCustomActions, :accessibilityElementDidBecomeFocused, :accessibilityElementDidLoseFocus, :accessibilityElementIsFocused, :accessibilityAssistiveTechnologyFocusedIdentifiers, :accessibilityFrame, :storedAccessibilityViewIsModal, :storedAccessibilityElementsHidden, :storedShouldGroupAccessibilityChildren, :storedAccessibilityNavigationStyle, :accessibilityHint, :accessibilityActivationPoint, :accessibilityTraits, :accessibilityLanguage, :accessibilityPath, :accessibilityViewIsModal, :accessibilityElementsHidden, :shouldGroupAccessibilityChildren, :accessibilityNavigationStyle, :storedAccessibilityTraits, :storedIsAccessibilityElement, :storedAccessibilityFrame, :storedAccessibilityActivationPoint, :accessibilityHeaderElements, :"setAccessibilityViewIsModal:", :"setAccessibilityHint:", :"setAccessibilityFrame:", :"setAccessibilityPath:", :"setAccessibilityActivationPoint:", :"setAccessibilityTraits:", :"setIsAccessibilityElement:", :"setAccessibilityContainer:", :"setAccessibilityLanguage:", :"setShouldGroupAccessibilityChildren:", :"setAccessibilityNavigationStyle:", :"setAccessibilityHeaderElements:", :"setAccessibilityElementsHidden:", :"setAccessibilityLabel:", :accessibilityValue, :"setAccessibilityValue:", :accessibilityLabel, :isAccessibilityElement, :accessibilityContainer, :awakeFromNib, :prepareForInterfaceBuilder, :CalClassName, :"performBlockOnMainThreadSynchronously:", :isNull, :"CKAssignToContainerWithID:", :CKDescription, :CKPropertiesDescription, :"cplIsEqual:", :cplHash, :cplFullDescription, :"cplEncodePropertiesWithCoder:", :"cplDecodePropertiesFromCoder:", :"cplCopyPropertiesFromObject:", :"cplSpecialIsEqual:", :cplSpecialHash, :"cplProperties:areEqualToPropertiesOf:", :"cplProperties:areEqualToPropertiesOf:differingProperty:", :cplDeepCopy, :"cplCopyProperties:fromObject:", :"storedClassNameForCPLArchiver:", :"plistArchiveWithCPLArchiver:", :"initWithCPLArchiver:", :"cl_json_serializeValue:", :cl_json_serializeKey, :"postNotificationWithDescription:", :okToNotifyFromThisThread, :"fromNotifySafeThreadPerformSelector:withObject:", :allowSafePerformSelector, :disallowSafePerformSelector, :"fromNotifySafeThreadPostNotificationName:object:userInfo:", :"fromMainThreadPostNotificationName:object:userInfo:", :blockingMainThreadProxy, :"delayedProxy:", :mainThreadProxy, :releaseOnMainThread, :sbs_isPlistableType, :"encodeWithCAMLWriter:", :"CAMLTypeForKey:", :CAMLType, :"CA_addValue:multipliedBy:", :"CA_interpolateValue:byFraction:", :"CA_roundToIntegerFromValue:", :"CA_distanceToValue:", :"CA_interpolateValues:::interpolator:", :CA_copyRenderValue, :CA_prepareRenderValue, :mf_lock, :mf_unlock, :mf_tryLock, :mf_lockOrdering, :mf_strictLockOrdering, :mf_exclusiveLocks, :mf_lockWithPriority, :mf_tryLockWithPriority, :"mf_observeKeyPath:options:usingBlock:", :pep_onMainThread, :"pep_onThread:", :"pep_onThread:immediateForMatchingThread:", :"pep_onOperationQueue:priority:", :pep_onDetachedThread, :"pep_onOperationQueue:", :"pep_getInvocation:", :"pep_afterDelay:", :pep_onMainThreadIfNecessary, :"bs_performSynchronously:", :"bs_performSynchronously:timeout:", :bs_encoded, :bs_isPlistableType, :bs_secureEncoded, :"performSelector:withObject:afterDelay:ignoreMenuTracking:", :classForPortCoder, :"replacementObjectForPortCoder:", :"methodDescriptionForSelector:", :"addObserver:", :"removeObservation:", :"receiveObservedValue:", :"receiveObservedError:", :finishObserving, :"addChainedObservers:", :"addObservationTransformer:", :"addObserverBlock:", :"performSelector:onThread:withObject:waitUntilDone:modes:", :"performSelectorOnMainThread:withObject:waitUntilDone:", :"performSelectorInBackground:withObject:", :"performSelectorOnMainThread:withObject:waitUntilDone:modes:", :"performSelector:onThread:withObject:waitUntilDone:", :"performSelector:withObject:afterDelay:inModes:", :"performSelector:withObject:afterDelay:", :"performSelector:object:afterDelay:", :"addObserver:forObservableKeyPath:", :"setObservation:forObservingKeyPath:", :"removeObservation:forObservableKeyPath:", :autoContentAccessingProxy, :classForCoder, :"replacementObjectForCoder:", :"awakeAfterUsingCoder:", :"implementsSelector:", :classForKeyedArchiver, :"replacementObjectForKeyedArchiver:", :"setObservationInfo:", :observationInfo, :"willChangeValueForKey:", :"didChangeValueForKey:", :"willChange:valuesAtIndexes:forKey:", :"didChange:valuesAtIndexes:forKey:", :"willChangeValueForKey:withSetMutation:usingObjects:", :"didChangeValueForKey:withSetMutation:usingObjects:", :"removeObserver:forKeyPath:context:", :"addObserver:forKeyPath:options:context:", :"removeObserver:forKeyPath:", :"observeValueForKeyPath:ofObject:change:context:", :"setValue:forKey:", :"valueForUndefinedKey:", :"setValue:forUndefinedKey:", :"setNilValueForKey:", :"setValue:forKeyPath:", :"validateValue:forKeyPath:error:", :"validateValue:forKey:error:", :"mutableArrayValueForKeyPath:", :"mutableArrayValueForKey:", :"mutableOrderedSetValueForKeyPath:", :"mutableOrderedSetValueForKey:", :"mutableSetValueForKeyPath:", :"mutableSetValueForKey:", :"valueForKey:", :"valueForKeyPath:", :"setValuesForKeysWithDictionary:", :"dictionaryWithValuesForKeys:", :"replacementObjectForArchiver:", :classForArchiver, :isNSString__, :isNSNumber__, :isNSArray__, :isNSDictionary__, :isNSData__, :isNSOrderedSet__, :isNSSet__, :isNSDate__, :isNSTimeZone__, :isNSValue__, :"doesNotRecognizeSelector:", :description, :"methodSignatureForSelector:", :retain, :release, :autorelease, :retainCount, :dealloc, :copy, :finalize, :"forwardInvocation:", :retainWeakReference, :allowsWeakReference, :isProxy, :"isMemberOfClass:", :superclass, :"isKindOfClass:", :mutableCopy, :"respondsToSelector:", :"performSelector:withObject:", :hash, :"isEqual:", :self, :"performSelector:", :"forwardingTargetForSelector:", :"methodForSelector:", :zone, :class, :debugDescription, :init, :"performSelector:withObject:withObject:", :isFault]
(main)> JojoModule.instance_methods
JojoModule.instance_methods
=> [:woof, :meth, :"conformsToProtocol:", :"mf_objectWithHighest:", :"mf_performOnewaySelectorInMainThread:withObject:withObject:", :"da_addNullRunLoopSourceAndPerformSelector:withObject:afterDelay:inModes:", :"da_performSelectorThatDoesntAffectRetainCount:withObject:", :pl_briefDescription, :MPMediaLibraryDataProviderSystemML3CoercedString, :MP_shortDescription, :"registerForTimeMarkerNotificationsIfNecessaryForPlayer:", :unregisterForTimeMarkerNotifications, :"cancelPreviousDispatchAsyncWithCancellationIdentifier:", :"dispatchAsyncWithCancellationIdentifier:delay:queue:block:", :"ICLogging_isLoggingEnabledAtLevel:", :"cn_updateDictionaryForKey:withChanges:", :ml_stringValueForSQL, :"ml_bindToSQLiteStatement:atPosition:", :"ml_matchesValue:usingComparison:", :"shouldUpdateFocusFromView:toView:heading:", :"willUpdateFocusInContext:withAnimationCoordinator:", :"willUpdateFocusToView:", :"didUpdateFocusFromView:", :className, :accessibilityIdentifier, :"setAccessibilityIdentifier:", :defaultAccessibilityTraits, :isAccessibilityElementByDefault, :isElementAccessibilityExposedToInterfaceBuilder, :"accessibilitySetIdentification:", :accessibilityElements, :"setAccessibilityElements:", :accessibilityElementCount, :"accessibilityElementAtIndex:", :"indexOfAccessibilityElement:", :accessibilityIncrement, :accessibilityDecrement, :"accessibilityScroll:", :accessibilityPerformEscape, :accessibilityPerformMagicTap, :accessibilityActivate, :"setAccessibilityCustomActions:", :accessibilityCustomActions, :accessibilityElementDidBecomeFocused, :accessibilityElementDidLoseFocus, :accessibilityElementIsFocused, :accessibilityAssistiveTechnologyFocusedIdentifiers, :accessibilityFrame, :storedAccessibilityViewIsModal, :storedAccessibilityElementsHidden, :storedShouldGroupAccessibilityChildren, :storedAccessibilityNavigationStyle, :accessibilityHint, :accessibilityActivationPoint, :accessibilityTraits, :accessibilityLanguage, :accessibilityPath, :accessibilityViewIsModal, :accessibilityElementsHidden, :shouldGroupAccessibilityChildren, :accessibilityNavigationStyle, :storedAccessibilityTraits, :storedIsAccessibilityElement, :storedAccessibilityFrame, :storedAccessibilityActivationPoint, :accessibilityHeaderElements, :"setAccessibilityViewIsModal:", :"setAccessibilityHint:", :"setAccessibilityFrame:", :"setAccessibilityPath:", :"setAccessibilityActivationPoint:", :"setAccessibilityTraits:", :"setIsAccessibilityElement:", :"setAccessibilityContainer:", :"setAccessibilityLanguage:", :"setShouldGroupAccessibilityChildren:", :"setAccessibilityNavigationStyle:", :"setAccessibilityHeaderElements:", :"setAccessibilityElementsHidden:", :"setAccessibilityLabel:", :accessibilityValue, :"setAccessibilityValue:", :accessibilityLabel, :isAccessibilityElement, :accessibilityContainer, :awakeFromNib, :prepareForInterfaceBuilder, :CalClassName, :"performBlockOnMainThreadSynchronously:", :isNull, :"CKAssignToContainerWithID:", :CKDescription, :CKPropertiesDescription, :"cplIsEqual:", :cplHash, :cplFullDescription, :"cplEncodePropertiesWithCoder:", :"cplDecodePropertiesFromCoder:", :"cplCopyPropertiesFromObject:", :"cplSpecialIsEqual:", :cplSpecialHash, :"cplProperties:areEqualToPropertiesOf:", :"cplProperties:areEqualToPropertiesOf:differingProperty:", :cplDeepCopy, :"cplCopyProperties:fromObject:", :"storedClassNameForCPLArchiver:", :"plistArchiveWithCPLArchiver:", :"initWithCPLArchiver:", :"cl_json_serializeValue:", :cl_json_serializeKey, :"postNotificationWithDescription:", :okToNotifyFromThisThread, :"fromNotifySafeThreadPerformSelector:withObject:", :allowSafePerformSelector, :disallowSafePerformSelector, :"fromNotifySafeThreadPostNotificationName:object:userInfo:", :"fromMainThreadPostNotificationName:object:userInfo:", :blockingMainThreadProxy, :"delayedProxy:", :mainThreadProxy, :releaseOnMainThread, :sbs_isPlistableType, :"encodeWithCAMLWriter:", :"CAMLTypeForKey:", :CAMLType, :"CA_addValue:multipliedBy:", :"CA_interpolateValue:byFraction:", :"CA_roundToIntegerFromValue:", :"CA_distanceToValue:", :"CA_interpolateValues:::interpolator:", :CA_copyRenderValue, :CA_prepareRenderValue, :mf_lock, :mf_unlock, :mf_tryLock, :mf_lockOrdering, :mf_strictLockOrdering, :mf_exclusiveLocks, :mf_lockWithPriority, :mf_tryLockWithPriority, :"mf_observeKeyPath:options:usingBlock:", :pep_onMainThread, :"pep_onThread:", :"pep_onThread:immediateForMatchingThread:", :"pep_onOperationQueue:priority:", :pep_onDetachedThread, :"pep_onOperationQueue:", :"pep_getInvocation:", :"pep_afterDelay:", :pep_onMainThreadIfNecessary, :"bs_performSynchronously:", :"bs_performSynchronously:timeout:", :bs_encoded, :bs_isPlistableType, :bs_secureEncoded, :"performSelector:withObject:afterDelay:ignoreMenuTracking:", :classForPortCoder, :"replacementObjectForPortCoder:", :"methodDescriptionForSelector:", :"addObserver:", :"removeObservation:", :"receiveObservedValue:", :"receiveObservedError:", :finishObserving, :"addChainedObservers:", :"addObservationTransformer:", :"addObserverBlock:", :"performSelector:onThread:withObject:waitUntilDone:modes:", :"performSelectorOnMainThread:withObject:waitUntilDone:", :"performSelectorInBackground:withObject:", :"performSelectorOnMainThread:withObject:waitUntilDone:modes:", :"performSelector:onThread:withObject:waitUntilDone:", :"performSelector:withObject:afterDelay:inModes:", :"performSelector:withObject:afterDelay:", :"performSelector:object:afterDelay:", :"addObserver:forObservableKeyPath:", :"setObservation:forObservingKeyPath:", :"removeObservation:forObservableKeyPath:", :autoContentAccessingProxy, :classForCoder, :"replacementObjectForCoder:", :"awakeAfterUsingCoder:", :"implementsSelector:", :classForKeyedArchiver, :"replacementObjectForKeyedArchiver:", :"setObservationInfo:", :observationInfo, :"willChangeValueForKey:", :"didChangeValueForKey:", :"willChange:valuesAtIndexes:forKey:", :"didChange:valuesAtIndexes:forKey:", :"willChangeValueForKey:withSetMutation:usingObjects:", :"didChangeValueForKey:withSetMutation:usingObjects:", :"removeObserver:forKeyPath:context:", :"addObserver:forKeyPath:options:context:", :"removeObserver:forKeyPath:", :"observeValueForKeyPath:ofObject:change:context:", :"setValue:forKey:", :"valueForUndefinedKey:", :"setValue:forUndefinedKey:", :"setNilValueForKey:", :"setValue:forKeyPath:", :"validateValue:forKeyPath:error:", :"validateValue:forKey:error:", :"mutableArrayValueForKeyPath:", :"mutableArrayValueForKey:", :"mutableOrderedSetValueForKeyPath:", :"mutableOrderedSetValueForKey:", :"mutableSetValueForKeyPath:", :"mutableSetValueForKey:", :"valueForKey:", :"valueForKeyPath:", :"setValuesForKeysWithDictionary:", :"dictionaryWithValuesForKeys:", :"replacementObjectForArchiver:", :classForArchiver, :isNSString__, :isNSNumber__, :isNSArray__, :isNSDictionary__, :isNSData__, :isNSOrderedSet__, :isNSSet__, :isNSDate__, :isNSTimeZone__, :isNSValue__, :"doesNotRecognizeSelector:", :description, :"methodSignatureForSelector:", :retain, :release, :autorelease, :retainCount, :dealloc, :copy, :finalize, :"forwardInvocation:", :retainWeakReference, :allowsWeakReference, :isProxy, :"isMemberOfClass:", :superclass, :"isKindOfClass:", :mutableCopy, :"respondsToSelector:", :"performSelector:withObject:", :hash, :"isEqual:", :self, :"performSelector:", :"forwardingTargetForSelector:", :"methodForSelector:", :zone, :class, :debugDescription, :init, :"performSelector:withObject:withObject:", :isFault]
(main)> JojoModule.ancestors
JojoModule.ancestors
=> [JojoModule, Math]
(main)> JojoModule.included_modules
JojoModule.included_modules
=> [Math]
(main)>

**Comment by dgutov** [comment]
> looks like ObjectSpace is not available

That's not great. We're using ObjectSpace as the indexing solution. Without it, we'd have to scan the project and gems some other way, e.g. using Yard, and you won't be able to use the same interactive style of development (like reload a file in the repl to pick up the changes in its methods) available using "real" Ruby implementations.

Without it, completion and navigation can only work on methods where the target is self (in the absence of type inference), which is often handy, but doesn't help as often as one would hope.

> (main)> JojoModule#woof.source_location
JojoModule#woof.source_location

This doesn't look right. You should try `JojoModule.instance_method(:woof).source_location`.

Anyway, until we implement a different indexer (no estimates), it doesn't seem like Robe is going to be too useful in RubyMotion development. Sorry.

You can try to see what currently works by evaluating `(run-ruby "command to run rubymotion console")` and then doing `M-x robe-start`.

**Comment by jojojames** [comment]
Yeah, looks like it's a no go for now.

JojoModule.instance_method(:woof).source_location
JojoModule.instance_method(:woof).source_location
2016-05-09 17:54:51.493 client[79734:925397] undefined method `source_location' for #<UnboundMethod: JojoModule#woof> (NoMethodError)
=> #<NoMethodError: undefined method `source_location' for #<UnboundMethod: JojoModule#woof>>

Doing this -> 'You can try to see what currently works by evaluating (run-ruby "command to run rubymotion console") and then doing M-x robe-start.'

just results in Emacs hanging which then requires a process kill/force quit.

**Comment by dgutov** [comment]
OK, non-working `source-location` means any possible support is far off for now.

Thank you for investigating. Maybe we could revisit this later.
