### ISSUE TITLE
[Feature Request] Run irb(or pry) with -f to suppress read of ~/.irbrc(or .pryrc)

### ISSUE THREAD

**Issue by zw963** [dgutov/robe#90]
This REPL only purpose is for robe use, I think not load any rc is better ?

**Comment by dgutov** [comment]
Not a good idea, IMO.

Better, see https://github.com/nonsequitur/inf-ruby/#bugs for the way to structure the `rc` files to execute some code only when inside (or outside) of Emacs.

**Comment by zw963** [comment]
Thanks, it help me a lot.
