### ISSUE TITLE
Some ActiveRecord class methods aren't offered as completions

### ISSUE THREAD

**Issue by ypresto** [dgutov/robe#92]
With rails console:

![image](https://cloud.githubusercontent.com/assets/400558/17084158/dd8acf06-51f1-11e6-8466-f702f4a6581a.png)

But in Atom `find` and `find_by` aren't shown:

![image](https://cloud.githubusercontent.com/assets/400558/17084150/c1370888-51f1-11e6-8d1f-75503124ddb9.png)

**Comment by dgutov** [comment]
Hi!

What version of ActiveRecord is this? Seems to work fine in Emacs with 4.2.5 and 4.0.4.

**Comment by ypresto** [comment]
I'm using 4.2.6.
URL is like this: `http://localhost:58287/complete_method/find/User/-/false`

**Comment by dgutov** [comment]
The URL should be `http://localhost:58287/complete_method/find/User/-/false`. `false` is not the same as `-`, see `Robe::Sash#call` (sorry about the awkward API).

**Comment by ypresto** [comment]
Ahhhh, I was misunderstanding about emacs..!
So, it does not have `false` and below snippet in `defun robe-call-context` will set `nil` instead of it.

```
(instance (unless target (second ctx))))
```

(Also, false in URL will be treated as string of `"false"` so it never works :)

Thanks, it is working perfectly with `-`...!!!

**Comment by ypresto** [comment]
(Also misunderstood about below snippet. That is `yes` for true and `-` for empty.)

```
                                   (cond ((eq arg t) "yes")
                                         ((plusp (length arg))
                                          (url-hexify-string arg))
                                         (t "-")))
```
