### ISSUE TITLE
Cannot start robe in windows using pry

### ISSUE THREAD

**Issue by yorodm** [dgutov/robe#97]
When having pry as a dependency in my Gemfile, robe-start hangs up forever. I'm using Ruby 2.3 with Pry 0.10, and Emacs 24.

**Comment by dgutov** [comment]
Does `M-x inf-ruby-console-auto` complete okay?

**Comment by yorodm** [comment]
`M-x inf-ruby-console-auto` launches Pry, but has no completion

**Comment by dgutov** [comment]
OK, does `ruby-send-region` work okay after that? In normal Ruby buffers.

**Comment by yorodm** [comment]
It doesn't seem to be working, funny thing is if I just `M-x inf-ruby` it runs irb and everything works ok so I guess the problem is more on the `inf-ruby` ruby side

**Comment by dgutov** [comment]
Or its Pry integration. So you might want to move this issue there.

By the way, if you see any weird characters in the REPL with Pry, try the [instructions at the end here](https://github.com/nonsequitur/inf-ruby/#bugs).

**Comment by dgutov** [comment]
Not our bug, closing.
